//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 06:07:01 PM EST 
//


package m3x.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnimationTargetType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AnimationTargetType">
 *   &lt;restriction base="{}String">
 *     &lt;enumeration value="ALPHA"/>
 *     &lt;enumeration value="AMBIENT_COLOR"/>
 *     &lt;enumeration value="ANIMATABILITY"/>
 *     &lt;enumeration value="ANIMATION_POSITION"/>
 *     &lt;enumeration value="ANIMATION_SPEED"/>
 *     &lt;enumeration value="ANIMATION_WEIGHT"/>
 *     &lt;enumeration value="BOUNDING_BOX"/>
 *     &lt;enumeration value="BOUNDING_SPHERE"/>
 *     &lt;enumeration value="COLOR"/>
 *     &lt;enumeration value="CROP"/>
 *     &lt;enumeration value="DENSITY"/>
 *     &lt;enumeration value="DEPTH"/>
 *     &lt;enumeration value="DIFFUSE_COLOR"/>
 *     &lt;enumeration value="EMISSIVE_COLOR"/>
 *     &lt;enumeration value="FAR_DISTANCE"/>
 *     &lt;enumeration value="FIELD_OF_VIEW"/>
 *     &lt;enumeration value="INTENSITY"/>
 *     &lt;enumeration value="MORPH_WEIGHTS"/>
 *     &lt;enumeration value="NEAR_DISTANCE"/>
 *     &lt;enumeration value="ORIENTATION"/>
 *     &lt;enumeration value="PICKABILITY"/>
 *     &lt;enumeration value="POINT_SIZE"/>
 *     &lt;enumeration value="SCALE"/>
 *     &lt;enumeration value="SHININESS"/>
 *     &lt;enumeration value="SPECULAR_COLOR"/>
 *     &lt;enumeration value="SPOT_ANGLE"/>
 *     &lt;enumeration value="SPOT_EXPONENT"/>
 *     &lt;enumeration value="STENCIL"/>
 *     &lt;enumeration value="TRANSLATION"/>
 *     &lt;enumeration value="VISIBILITY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AnimationTargetType")
@XmlEnum
public enum AnimationTargetType {


    /**
     * 
     *                         Targets the node ALPHA value of the target. Only valid for Node targets.
     *                     
     * 
     */
    ALPHA,

    /**
     * 
     *                         Targets Material ambient color value. Only valid for Material targets.
     *                         Since M3G 1.0
     *                     
     * 
     */
    AMBIENT_COLOR,

    /**
     * 
     *                         Targets Object3D animatability. Only valid for Object3D targets.
     *                         Since M3G 2.0
     *                     
     * 
     */
    ANIMATABILITY,

    /**
     * 
     *                         Targets reference position of controller objects. Only valid for AnimationController targets.
     *                         Since M3G 2.0
     *                     
     * 
     */
    ANIMATION_POSITION,

    /**
     * 
     *                         Targets playback speed of controller objects. Only valid for AnimationController targets.
     *                         Since M3G 2.0
     *                     
     * 
     */
    ANIMATION_SPEED,

    /**
     * 
     *                         Targets blending weight of controller objects. Only valid for AnimationController targets.
     *                         Since M3G 2.0
     *                     
     * 
     */
    ANIMATION_WEIGHT,

    /**
     * 
     *                         Targets bounding box information of node objects. Only valid for Node targets.
     *                         Since M3G 2.0
     *                     
     * 
     */
    BOUNDING_BOX,

    /**
     * 
     *                         Targets bounding sphere information of node objects. Only valid for Node targets.
     *                         Since M3G 2.0
     *                     
     * 
     */
    BOUNDING_SPHERE,

    /**
     * 
     *                         Targets the color of Light, Background, Fog, Texture2D or VertexBuffer objects.
     *                         Since M3G 2.0
     *                     
     * 
     */
    COLOR,

    /**
     * 
     *                         Targets sprite crop information.
     *                         Deprecated in M3G 2.0
     *                     
     * 
     */
    CROP,
    DENSITY,
    DEPTH,
    DIFFUSE_COLOR,
    EMISSIVE_COLOR,
    FAR_DISTANCE,
    FIELD_OF_VIEW,
    INTENSITY,
    MORPH_WEIGHTS,
    NEAR_DISTANCE,
    ORIENTATION,
    PICKABILITY,
    POINT_SIZE,
    SCALE,
    SHININESS,
    SPECULAR_COLOR,
    SPOT_ANGLE,
    SPOT_EXPONENT,
    STENCIL,
    TRANSLATION,
    VISIBILITY;

    public String value() {
        return name();
    }

    public static AnimationTargetType fromValue(String v) {
        return valueOf(v);
    }

}
