//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.02 at 11:04:04 PM EST 
//


package m3x.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}Object3DType">
 *       &lt;sequence>
 *         &lt;element ref="{}KeyframeSequenceInstance" minOccurs="0"/>
 *         &lt;element ref="{}AnimationControllerInstance" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="property" type="{}AnimationTargetType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "keyframeSequenceInstance",
    "animationControllerInstance"
})
@XmlRootElement(name = "AnimationTrack")
public class AnimationTrack
    extends Object3DType
{

    @XmlElement(name = "KeyframeSequenceInstance")
    protected KeyframeSequenceInstance keyframeSequenceInstance;
    @XmlElement(name = "AnimationControllerInstance")
    protected AnimationControllerInstance animationControllerInstance;
    @XmlAttribute
    protected AnimationTargetType property;

    /**
     * Gets the value of the keyframeSequenceInstance property.
     * 
     * @return
     *     possible object is
     *     {@link KeyframeSequenceInstance }
     *     
     */
    public KeyframeSequenceInstance getKeyframeSequenceInstance() {
        return keyframeSequenceInstance;
    }

    /**
     * Sets the value of the keyframeSequenceInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyframeSequenceInstance }
     *     
     */
    public void setKeyframeSequenceInstance(KeyframeSequenceInstance value) {
        this.keyframeSequenceInstance = value;
    }

    /**
     * Gets the value of the animationControllerInstance property.
     * 
     * @return
     *     possible object is
     *     {@link AnimationControllerInstance }
     *     
     */
    public AnimationControllerInstance getAnimationControllerInstance() {
        return animationControllerInstance;
    }

    /**
     * Sets the value of the animationControllerInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnimationControllerInstance }
     *     
     */
    public void setAnimationControllerInstance(AnimationControllerInstance value) {
        this.animationControllerInstance = value;
    }

    /**
     * Gets the value of the property property.
     * 
     * @return
     *     possible object is
     *     {@link AnimationTargetType }
     *     
     */
    public AnimationTargetType getProperty() {
        return property;
    }

    /**
     * Sets the value of the property property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnimationTargetType }
     *     
     */
    public void setProperty(AnimationTargetType value) {
        this.property = value;
    }

}
