//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 06:07:01 PM EST 
//


package m3x.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}Object3DType">
 *       &lt;attribute name="speed" type="{}Float32" />
 *       &lt;attribute name="weight" type="{}Float32" />
 *       &lt;attribute name="activeIntervalStart" type="{}Int32" />
 *       &lt;attribute name="activeIntervalEnd" type="{}Int32" />
 *       &lt;attribute name="referenceSequenceTime" type="{}Float32" />
 *       &lt;attribute name="referenceWorldTime" type="{}Int32" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "AnimationController")
public class AnimationController
    extends Object3DType
{

    @XmlAttribute
    protected Float speed;
    @XmlAttribute
    protected Float weight;
    @XmlAttribute
    protected Integer activeIntervalStart;
    @XmlAttribute
    protected Integer activeIntervalEnd;
    @XmlAttribute
    protected Float referenceSequenceTime;
    @XmlAttribute
    protected Integer referenceWorldTime;

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSpeed(Float value) {
        this.speed = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setWeight(Float value) {
        this.weight = value;
    }

    /**
     * Gets the value of the activeIntervalStart property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getActiveIntervalStart() {
        return activeIntervalStart;
    }

    /**
     * Sets the value of the activeIntervalStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setActiveIntervalStart(Integer value) {
        this.activeIntervalStart = value;
    }

    /**
     * Gets the value of the activeIntervalEnd property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getActiveIntervalEnd() {
        return activeIntervalEnd;
    }

    /**
     * Sets the value of the activeIntervalEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setActiveIntervalEnd(Integer value) {
        this.activeIntervalEnd = value;
    }

    /**
     * Gets the value of the referenceSequenceTime property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getReferenceSequenceTime() {
        return referenceSequenceTime;
    }

    /**
     * Sets the value of the referenceSequenceTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setReferenceSequenceTime(Float value) {
        this.referenceSequenceTime = value;
    }

    /**
     * Gets the value of the referenceWorldTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReferenceWorldTime() {
        return referenceWorldTime;
    }

    /**
     * Sets the value of the referenceWorldTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReferenceWorldTime(Integer value) {
        this.referenceWorldTime = value;
    }

}
