//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 08:26:55 PM EST 
//


package m3x.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}Object3DType">
 *       &lt;sequence>
 *         &lt;element ref="{}Image2DInstance" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="backgroundColor" type="{}ColorRGBA" default="0 0 0 255" />
 *       &lt;attribute name="backgroundImageModeX" type="{}BackgroundRepeatType" />
 *       &lt;attribute name="backgroundImageModeY" type="{}BackgroundRepeatType" />
 *       &lt;attribute name="cropX" type="{}Int32" />
 *       &lt;attribute name="cropY" type="{}Int32" />
 *       &lt;attribute name="cropWidth" type="{}Int32" />
 *       &lt;attribute name="cropHeight" type="{}Int32" />
 *       &lt;attribute name="depthClearEnabled" type="{}Boolean" />
 *       &lt;attribute name="colorClearEnabled" type="{}Boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "image2DInstance"
})
@XmlRootElement(name = "Background")
public class Background
    extends Object3DType
{

    @XmlElement(name = "Image2DInstance")
    protected Image2DInstance image2DInstance;
    @XmlAttribute
    protected List<Short> backgroundColor;
    @XmlAttribute
    protected BackgroundRepeatType backgroundImageModeX;
    @XmlAttribute
    protected BackgroundRepeatType backgroundImageModeY;
    @XmlAttribute
    protected Integer cropX;
    @XmlAttribute
    protected Integer cropY;
    @XmlAttribute
    protected Integer cropWidth;
    @XmlAttribute
    protected Integer cropHeight;
    @XmlAttribute
    protected Boolean depthClearEnabled;
    @XmlAttribute
    protected Boolean colorClearEnabled;

    /**
     * Gets the value of the image2DInstance property.
     * 
     * @return
     *     possible object is
     *     {@link Image2DInstance }
     *     
     */
    public Image2DInstance getImage2DInstance() {
        return image2DInstance;
    }

    /**
     * Sets the value of the image2DInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Image2DInstance }
     *     
     */
    public void setImage2DInstance(Image2DInstance value) {
        this.image2DInstance = value;
    }

    /**
     * Gets the value of the backgroundColor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the backgroundColor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBackgroundColor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Short }
     * 
     * 
     */
    public List<Short> getBackgroundColor() {
        if (backgroundColor == null) {
            backgroundColor = new ArrayList<Short>();
        }
        return this.backgroundColor;
    }

    /**
     * Gets the value of the backgroundImageModeX property.
     * 
     * @return
     *     possible object is
     *     {@link BackgroundRepeatType }
     *     
     */
    public BackgroundRepeatType getBackgroundImageModeX() {
        return backgroundImageModeX;
    }

    /**
     * Sets the value of the backgroundImageModeX property.
     * 
     * @param value
     *     allowed object is
     *     {@link BackgroundRepeatType }
     *     
     */
    public void setBackgroundImageModeX(BackgroundRepeatType value) {
        this.backgroundImageModeX = value;
    }

    /**
     * Gets the value of the backgroundImageModeY property.
     * 
     * @return
     *     possible object is
     *     {@link BackgroundRepeatType }
     *     
     */
    public BackgroundRepeatType getBackgroundImageModeY() {
        return backgroundImageModeY;
    }

    /**
     * Sets the value of the backgroundImageModeY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BackgroundRepeatType }
     *     
     */
    public void setBackgroundImageModeY(BackgroundRepeatType value) {
        this.backgroundImageModeY = value;
    }

    /**
     * Gets the value of the cropX property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCropX() {
        return cropX;
    }

    /**
     * Sets the value of the cropX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCropX(Integer value) {
        this.cropX = value;
    }

    /**
     * Gets the value of the cropY property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCropY() {
        return cropY;
    }

    /**
     * Sets the value of the cropY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCropY(Integer value) {
        this.cropY = value;
    }

    /**
     * Gets the value of the cropWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCropWidth() {
        return cropWidth;
    }

    /**
     * Sets the value of the cropWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCropWidth(Integer value) {
        this.cropWidth = value;
    }

    /**
     * Gets the value of the cropHeight property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCropHeight() {
        return cropHeight;
    }

    /**
     * Sets the value of the cropHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCropHeight(Integer value) {
        this.cropHeight = value;
    }

    /**
     * Gets the value of the depthClearEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDepthClearEnabled() {
        return depthClearEnabled;
    }

    /**
     * Sets the value of the depthClearEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDepthClearEnabled(Boolean value) {
        this.depthClearEnabled = value;
    }

    /**
     * Gets the value of the colorClearEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isColorClearEnabled() {
        return colorClearEnabled;
    }

    /**
     * Sets the value of the colorClearEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setColorClearEnabled(Boolean value) {
        this.colorClearEnabled = value;
    }

}
