//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.02 at 11:04:04 PM EST 
//


package m3x.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}Object3DType">
 *       &lt;sequence>
 *         &lt;element ref="{}Image2DInstance" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="color" type="{}int" default="0" />
 *       &lt;attribute name="modeX" type="{}BackgroundRepeatType" />
 *       &lt;attribute name="modeY" type="{}BackgroundRepeatType" />
 *       &lt;attribute name="cropX" type="{}int" />
 *       &lt;attribute name="cropY" type="{}int" />
 *       &lt;attribute name="cropWidth" type="{}int" />
 *       &lt;attribute name="cropHeight" type="{}int" />
 *       &lt;attribute name="depthClear" type="{}bool" />
 *       &lt;attribute name="colorClear" type="{}bool" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "image2DInstance"
})
@XmlRootElement(name = "Background")
public class Background
    extends Object3DType
{

    @XmlElement(name = "Image2DInstance")
    protected Image2DInstance image2DInstance;
    @XmlAttribute
    protected Long color;
    @XmlAttribute
    protected BackgroundRepeatType modeX;
    @XmlAttribute
    protected BackgroundRepeatType modeY;
    @XmlAttribute
    protected Long cropX;
    @XmlAttribute
    protected Long cropY;
    @XmlAttribute
    protected Long cropWidth;
    @XmlAttribute
    protected Long cropHeight;
    @XmlAttribute
    protected Boolean depthClear;
    @XmlAttribute
    protected Boolean colorClear;

    /**
     * Gets the value of the image2DInstance property.
     * 
     * @return
     *     possible object is
     *     {@link Image2DInstance }
     *     
     */
    public Image2DInstance getImage2DInstance() {
        return image2DInstance;
    }

    /**
     * Sets the value of the image2DInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Image2DInstance }
     *     
     */
    public void setImage2DInstance(Image2DInstance value) {
        this.image2DInstance = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getColor() {
        if (color == null) {
            return  0L;
        } else {
            return color;
        }
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setColor(Long value) {
        this.color = value;
    }

    /**
     * Gets the value of the modeX property.
     * 
     * @return
     *     possible object is
     *     {@link BackgroundRepeatType }
     *     
     */
    public BackgroundRepeatType getModeX() {
        return modeX;
    }

    /**
     * Sets the value of the modeX property.
     * 
     * @param value
     *     allowed object is
     *     {@link BackgroundRepeatType }
     *     
     */
    public void setModeX(BackgroundRepeatType value) {
        this.modeX = value;
    }

    /**
     * Gets the value of the modeY property.
     * 
     * @return
     *     possible object is
     *     {@link BackgroundRepeatType }
     *     
     */
    public BackgroundRepeatType getModeY() {
        return modeY;
    }

    /**
     * Sets the value of the modeY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BackgroundRepeatType }
     *     
     */
    public void setModeY(BackgroundRepeatType value) {
        this.modeY = value;
    }

    /**
     * Gets the value of the cropX property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCropX() {
        return cropX;
    }

    /**
     * Sets the value of the cropX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCropX(Long value) {
        this.cropX = value;
    }

    /**
     * Gets the value of the cropY property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCropY() {
        return cropY;
    }

    /**
     * Sets the value of the cropY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCropY(Long value) {
        this.cropY = value;
    }

    /**
     * Gets the value of the cropWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCropWidth() {
        return cropWidth;
    }

    /**
     * Sets the value of the cropWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCropWidth(Long value) {
        this.cropWidth = value;
    }

    /**
     * Gets the value of the cropHeight property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCropHeight() {
        return cropHeight;
    }

    /**
     * Sets the value of the cropHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCropHeight(Long value) {
        this.cropHeight = value;
    }

    /**
     * Gets the value of the depthClear property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDepthClear() {
        return depthClear;
    }

    /**
     * Sets the value of the depthClear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDepthClear(Boolean value) {
        this.depthClear = value;
    }

    /**
     * Gets the value of the colorClear property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isColorClear() {
        return colorClear;
    }

    /**
     * Sets the value of the colorClear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setColorClear(Boolean value) {
        this.colorClear = value;
    }

}
