//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 08:26:55 PM EST 
//


package m3x.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BlenderType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BlenderType">
 *   &lt;restriction base="{}String">
 *     &lt;enumeration value="ADD"/>
 *     &lt;enumeration value="CONSTANT_ALPHA"/>
 *     &lt;enumeration value="CONSTANT_COLOR"/>
 *     &lt;enumeration value="DST_ALPHA"/>
 *     &lt;enumeration value="DST_COLOR"/>
 *     &lt;enumeration value="ONE"/>
 *     &lt;enumeration value="ONE_MINUS_CONSTANT_ALPHA"/>
 *     &lt;enumeration value="ONE_MINUS_CONSTANT_COLOR"/>
 *     &lt;enumeration value="ONE_MINUS_DST_ALPHA"/>
 *     &lt;enumeration value="ONE_MINUS_DST_COLOR"/>
 *     &lt;enumeration value="ONE_MINUS_SRC_ALPHA"/>
 *     &lt;enumeration value="ONE_MINUS_SRC_COLOR"/>
 *     &lt;enumeration value="REVERSE_SUBTRACT"/>
 *     &lt;enumeration value="SRC_ALPHA"/>
 *     &lt;enumeration value="SRC_ALPHA_SATURATE"/>
 *     &lt;enumeration value="SRC_COLOR"/>
 *     &lt;enumeration value="SUBTRACT"/>
 *     &lt;enumeration value="ZERO"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BlenderType")
@XmlEnum
public enum BlenderType {

    ADD,
    CONSTANT_ALPHA,
    CONSTANT_COLOR,
    DST_ALPHA,
    DST_COLOR,
    ONE,
    ONE_MINUS_CONSTANT_ALPHA,
    ONE_MINUS_CONSTANT_COLOR,
    ONE_MINUS_DST_ALPHA,
    ONE_MINUS_DST_COLOR,
    ONE_MINUS_SRC_ALPHA,
    ONE_MINUS_SRC_COLOR,
    REVERSE_SUBTRACT,
    SRC_ALPHA,
    SRC_ALPHA_SATURATE,
    SRC_COLOR,
    SUBTRACT,
    ZERO;

    public String value() {
        return name();
    }

    public static BlenderType fromValue(String v) {
        return valueOf(v);
    }

}
