//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 06:17:17 PM EST 
//


package m3x.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}NodeType">
 *       &lt;sequence>
 *         &lt;element ref="{}ProjectionTransform" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="projectionType" type="{}CameraProjectionModeType" />
 *       &lt;attribute name="fovy" type="{}Float32" />
 *       &lt;attribute name="aspectRatio" type="{}Float32" />
 *       &lt;attribute name="near" type="{}Float32" />
 *       &lt;attribute name="far" type="{}Float32" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "projectionTransform"
})
@XmlRootElement(name = "Camera")
public class Camera
    extends NodeType
{

    @XmlList
    @XmlElement(name = "ProjectionTransform", type = Float.class)
    protected List<Float> projectionTransform;
    @XmlAttribute
    protected CameraProjectionModeType projectionType;
    @XmlAttribute
    protected Float fovy;
    @XmlAttribute
    protected Float aspectRatio;
    @XmlAttribute
    protected Float near;
    @XmlAttribute
    protected Float far;

    /**
     * Gets the value of the projectionTransform property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the projectionTransform property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProjectionTransform().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Float }
     * 
     * 
     */
    public List<Float> getProjectionTransform() {
        if (projectionTransform == null) {
            projectionTransform = new ArrayList<Float>();
        }
        return this.projectionTransform;
    }

    /**
     * Gets the value of the projectionType property.
     * 
     * @return
     *     possible object is
     *     {@link CameraProjectionModeType }
     *     
     */
    public CameraProjectionModeType getProjectionType() {
        return projectionType;
    }

    /**
     * Sets the value of the projectionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CameraProjectionModeType }
     *     
     */
    public void setProjectionType(CameraProjectionModeType value) {
        this.projectionType = value;
    }

    /**
     * Gets the value of the fovy property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFovy() {
        return fovy;
    }

    /**
     * Sets the value of the fovy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFovy(Float value) {
        this.fovy = value;
    }

    /**
     * Gets the value of the aspectRatio property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getAspectRatio() {
        return aspectRatio;
    }

    /**
     * Sets the value of the aspectRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAspectRatio(Float value) {
        this.aspectRatio = value;
    }

    /**
     * Gets the value of the near property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getNear() {
        return near;
    }

    /**
     * Sets the value of the near property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setNear(Float value) {
        this.near = value;
    }

    /**
     * Gets the value of the far property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFar() {
        return far;
    }

    /**
     * Sets the value of the far property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFar(Float value) {
        this.far = value;
    }

}
