//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.02 at 11:04:04 PM EST 
//


package m3x.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}NodeType">
 *       &lt;sequence>
 *         &lt;element ref="{}ProjectionTransform" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="projection" type="{}CameraProjectionModeType" />
 *       &lt;attribute name="fovy" type="{}float" />
 *       &lt;attribute name="aspect" type="{}float" />
 *       &lt;attribute name="near" type="{}float" />
 *       &lt;attribute name="far" type="{}float" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "projectionTransform"
})
@XmlRootElement(name = "Camera")
public class Camera
    extends NodeType
{

    @XmlList
    @XmlElement(name = "ProjectionTransform", type = Double.class)
    protected List<Double> projectionTransform;
    @XmlAttribute
    protected CameraProjectionModeType projection;
    @XmlAttribute
    protected Double fovy;
    @XmlAttribute
    protected Double aspect;
    @XmlAttribute
    protected Double near;
    @XmlAttribute
    protected Double far;

    /**
     * Gets the value of the projectionTransform property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the projectionTransform property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProjectionTransform().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Double }
     * 
     * 
     */
    public List<Double> getProjectionTransform() {
        if (projectionTransform == null) {
            projectionTransform = new ArrayList<Double>();
        }
        return this.projectionTransform;
    }

    /**
     * Gets the value of the projection property.
     * 
     * @return
     *     possible object is
     *     {@link CameraProjectionModeType }
     *     
     */
    public CameraProjectionModeType getProjection() {
        return projection;
    }

    /**
     * Sets the value of the projection property.
     * 
     * @param value
     *     allowed object is
     *     {@link CameraProjectionModeType }
     *     
     */
    public void setProjection(CameraProjectionModeType value) {
        this.projection = value;
    }

    /**
     * Gets the value of the fovy property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFovy() {
        return fovy;
    }

    /**
     * Sets the value of the fovy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFovy(Double value) {
        this.fovy = value;
    }

    /**
     * Gets the value of the aspect property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAspect() {
        return aspect;
    }

    /**
     * Sets the value of the aspect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAspect(Double value) {
        this.aspect = value;
    }

    /**
     * Gets the value of the near property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getNear() {
        return near;
    }

    /**
     * Sets the value of the near property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setNear(Double value) {
        this.near = value;
    }

    /**
     * Gets the value of the far property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFar() {
        return far;
    }

    /**
     * Sets the value of the far property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFar(Double value) {
        this.far = value;
    }

}
