//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.02 at 11:04:04 PM EST 
//


package m3x.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}Object3DType">
 *       &lt;attribute name="depthTest" type="{}bool" />
 *       &lt;attribute name="depthWrite" type="{}bool" />
 *       &lt;attribute name="colorWrite" type="{}bool" />
 *       &lt;attribute name="alphaWrite" type="{}bool" />
 *       &lt;attribute name="blending" type="{}CompositingModeType" />
 *       &lt;attribute name="alphaThreshold" type="{}float" />
 *       &lt;attribute name="depthOffsetFactor" type="{}float" />
 *       &lt;attribute name="depthOffsetUnits" type="{}float" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "CompositingMode")
public class CompositingMode
    extends Object3DType
{

    @XmlAttribute
    protected Boolean depthTest;
    @XmlAttribute
    protected Boolean depthWrite;
    @XmlAttribute
    protected Boolean colorWrite;
    @XmlAttribute
    protected Boolean alphaWrite;
    @XmlAttribute
    protected CompositingModeType blending;
    @XmlAttribute
    protected Double alphaThreshold;
    @XmlAttribute
    protected Double depthOffsetFactor;
    @XmlAttribute
    protected Double depthOffsetUnits;

    /**
     * Gets the value of the depthTest property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDepthTest() {
        return depthTest;
    }

    /**
     * Sets the value of the depthTest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDepthTest(Boolean value) {
        this.depthTest = value;
    }

    /**
     * Gets the value of the depthWrite property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDepthWrite() {
        return depthWrite;
    }

    /**
     * Sets the value of the depthWrite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDepthWrite(Boolean value) {
        this.depthWrite = value;
    }

    /**
     * Gets the value of the colorWrite property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isColorWrite() {
        return colorWrite;
    }

    /**
     * Sets the value of the colorWrite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setColorWrite(Boolean value) {
        this.colorWrite = value;
    }

    /**
     * Gets the value of the alphaWrite property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAlphaWrite() {
        return alphaWrite;
    }

    /**
     * Sets the value of the alphaWrite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAlphaWrite(Boolean value) {
        this.alphaWrite = value;
    }

    /**
     * Gets the value of the blending property.
     * 
     * @return
     *     possible object is
     *     {@link CompositingModeType }
     *     
     */
    public CompositingModeType getBlending() {
        return blending;
    }

    /**
     * Sets the value of the blending property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompositingModeType }
     *     
     */
    public void setBlending(CompositingModeType value) {
        this.blending = value;
    }

    /**
     * Gets the value of the alphaThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAlphaThreshold() {
        return alphaThreshold;
    }

    /**
     * Sets the value of the alphaThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAlphaThreshold(Double value) {
        this.alphaThreshold = value;
    }

    /**
     * Gets the value of the depthOffsetFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDepthOffsetFactor() {
        return depthOffsetFactor;
    }

    /**
     * Sets the value of the depthOffsetFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDepthOffsetFactor(Double value) {
        this.depthOffsetFactor = value;
    }

    /**
     * Gets the value of the depthOffsetUnits property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDepthOffsetUnits() {
        return depthOffsetUnits;
    }

    /**
     * Sets the value of the depthOffsetUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDepthOffsetUnits(Double value) {
        this.depthOffsetUnits = value;
    }

}
