//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 08:26:55 PM EST 
//


package m3x.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}Object3DType">
 *       &lt;attribute name="depthTestEnabled" type="{}Boolean" />
 *       &lt;attribute name="depthWriteEnabled" type="{}Boolean" />
 *       &lt;attribute name="colorWriteEnabled" type="{}Boolean" />
 *       &lt;attribute name="alphaWriteEnabled" type="{}Boolean" />
 *       &lt;attribute name="blending" type="{}CompositingModeType" />
 *       &lt;attribute name="alphaThreshold" type="{}Float32" />
 *       &lt;attribute name="depthOffsetFactor" type="{}Float32" />
 *       &lt;attribute name="depthOffsetUnits" type="{}Float32" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "CompositingMode")
public class CompositingMode
    extends Object3DType
{

    @XmlAttribute
    protected Boolean depthTestEnabled;
    @XmlAttribute
    protected Boolean depthWriteEnabled;
    @XmlAttribute
    protected Boolean colorWriteEnabled;
    @XmlAttribute
    protected Boolean alphaWriteEnabled;
    @XmlAttribute
    protected CompositingModeType blending;
    @XmlAttribute
    protected Float alphaThreshold;
    @XmlAttribute
    protected Float depthOffsetFactor;
    @XmlAttribute
    protected Float depthOffsetUnits;

    /**
     * Gets the value of the depthTestEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDepthTestEnabled() {
        return depthTestEnabled;
    }

    /**
     * Sets the value of the depthTestEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDepthTestEnabled(Boolean value) {
        this.depthTestEnabled = value;
    }

    /**
     * Gets the value of the depthWriteEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDepthWriteEnabled() {
        return depthWriteEnabled;
    }

    /**
     * Sets the value of the depthWriteEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDepthWriteEnabled(Boolean value) {
        this.depthWriteEnabled = value;
    }

    /**
     * Gets the value of the colorWriteEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isColorWriteEnabled() {
        return colorWriteEnabled;
    }

    /**
     * Sets the value of the colorWriteEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setColorWriteEnabled(Boolean value) {
        this.colorWriteEnabled = value;
    }

    /**
     * Gets the value of the alphaWriteEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAlphaWriteEnabled() {
        return alphaWriteEnabled;
    }

    /**
     * Sets the value of the alphaWriteEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAlphaWriteEnabled(Boolean value) {
        this.alphaWriteEnabled = value;
    }

    /**
     * Gets the value of the blending property.
     * 
     * @return
     *     possible object is
     *     {@link CompositingModeType }
     *     
     */
    public CompositingModeType getBlending() {
        return blending;
    }

    /**
     * Sets the value of the blending property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompositingModeType }
     *     
     */
    public void setBlending(CompositingModeType value) {
        this.blending = value;
    }

    /**
     * Gets the value of the alphaThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getAlphaThreshold() {
        return alphaThreshold;
    }

    /**
     * Sets the value of the alphaThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAlphaThreshold(Float value) {
        this.alphaThreshold = value;
    }

    /**
     * Gets the value of the depthOffsetFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getDepthOffsetFactor() {
        return depthOffsetFactor;
    }

    /**
     * Sets the value of the depthOffsetFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDepthOffsetFactor(Float value) {
        this.depthOffsetFactor = value;
    }

    /**
     * Gets the value of the depthOffsetUnits property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getDepthOffsetUnits() {
        return depthOffsetUnits;
    }

    /**
     * Sets the value of the depthOffsetUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDepthOffsetUnits(Float value) {
        this.depthOffsetUnits = value;
    }

}
