//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.02 at 11:04:04 PM EST 
//


package m3x.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompositingModeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CompositingModeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ALPHA"/>
 *     &lt;enumeration value="ALPHA_ADD"/>
 *     &lt;enumeration value="ALPHA_PREMULTIPLY"/>
 *     &lt;enumeration value="ALPHA_DARKEN"/>
 *     &lt;enumeration value="MODULATE"/>
 *     &lt;enumeration value="MODULATE_X2"/>
 *     &lt;enumeration value="MODULATE_INV"/>
 *     &lt;enumeration value="REPLACE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CompositingModeType")
@XmlEnum
public enum CompositingModeType {

    ALPHA("ALPHA"),
    ALPHA_ADD("ALPHA_ADD"),
    ALPHA_PREMULTIPLY("ALPHA_PREMULTIPLY"),
    ALPHA_DARKEN("ALPHA_DARKEN"),
    MODULATE("MODULATE"),
    @XmlEnumValue("MODULATE_X2")
    MODULATE_X_2("MODULATE_X2"),
    MODULATE_INV("MODULATE_INV"),
    REPLACE("REPLACE");
    private final String value;

    CompositingModeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CompositingModeType fromValue(String v) {
        for (CompositingModeType c: CompositingModeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
