//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 08:26:55 PM EST 
//


package m3x.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}Object3DType">
 *       &lt;attribute name="color" type="{}ColorRGB" />
 *       &lt;attribute name="mode" type="{}FogEquationType" />
 *       &lt;attribute name="density" type="{}Float32" />
 *       &lt;attribute name="near" type="{}Float32" />
 *       &lt;attribute name="far" type="{}Float32" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Fog")
public class Fog
    extends Object3DType
{

    @XmlAttribute
    protected List<Short> color;
    @XmlAttribute
    protected FogEquationType mode;
    @XmlAttribute
    protected Float density;
    @XmlAttribute
    protected Float near;
    @XmlAttribute
    protected Float far;

    /**
     * Gets the value of the color property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the color property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Short }
     * 
     * 
     */
    public List<Short> getColor() {
        if (color == null) {
            color = new ArrayList<Short>();
        }
        return this.color;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link FogEquationType }
     *     
     */
    public FogEquationType getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link FogEquationType }
     *     
     */
    public void setMode(FogEquationType value) {
        this.mode = value;
    }

    /**
     * Gets the value of the density property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getDensity() {
        return density;
    }

    /**
     * Sets the value of the density property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDensity(Float value) {
        this.density = value;
    }

    /**
     * Gets the value of the near property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getNear() {
        return near;
    }

    /**
     * Sets the value of the near property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setNear(Float value) {
        this.near = value;
    }

    /**
     * Gets the value of the far property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFar() {
        return far;
    }

    /**
     * Sets the value of the far property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFar(Float value) {
        this.far = value;
    }

}
