//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 08:26:55 PM EST 
//


package m3x.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GroupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GroupType">
 *   &lt;complexContent>
 *     &lt;extension base="{}NodeType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;group ref="{}NodeElementGroup"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GroupType", propOrder = {
    "childNodes"
})
@XmlSeeAlso({
    World.class,
    Group.class
})
public class GroupType
    extends NodeType
{

    @XmlElements({
        @XmlElement(name = "Camera", type = Camera.class),
        @XmlElement(name = "Group", type = Group.class),
        @XmlElement(name = "Mesh", type = Mesh.class),
        @XmlElement(name = "Light", type = Light.class),
        @XmlElement(name = "SkinnedMesh", type = SkinnedMesh.class)
    })
    protected List<NodeType> childNodes;

    /**
     * Gets the value of the childNodes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the childNodes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChildNodes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Camera }
     * {@link Group }
     * {@link Mesh }
     * {@link Light }
     * {@link SkinnedMesh }
     * 
     * 
     */
    public List<NodeType> getChildNodes() {
        if (childNodes == null) {
            childNodes = new ArrayList<NodeType>();
        }
        return this.childNodes;
    }

}
