//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.02 at 11:04:04 PM EST 
//


package m3x.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GroupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GroupType">
 *   &lt;complexContent>
 *     &lt;extension base="{}NodeType">
 *       &lt;sequence>
 *         &lt;element ref="{}Camera" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Light" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Mesh" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}SkinnedMesh" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Group" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GroupType", propOrder = {
    "camera",
    "light",
    "mesh",
    "skinnedMesh",
    "group"
})
@XmlSeeAlso({
    World.class,
    Group.class
})
public class GroupType
    extends NodeType
{

    @XmlElement(name = "Camera")
    protected List<Camera> camera;
    @XmlElement(name = "Light")
    protected List<Light> light;
    @XmlElement(name = "Mesh")
    protected List<Mesh> mesh;
    @XmlElement(name = "SkinnedMesh")
    protected List<SkinnedMesh> skinnedMesh;
    @XmlElement(name = "Group")
    protected List<Group> group;

    /**
     * Gets the value of the camera property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the camera property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCamera().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Camera }
     * 
     * 
     */
    public List<Camera> getCamera() {
        if (camera == null) {
            camera = new ArrayList<Camera>();
        }
        return this.camera;
    }

    /**
     * Gets the value of the light property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the light property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLight().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Light }
     * 
     * 
     */
    public List<Light> getLight() {
        if (light == null) {
            light = new ArrayList<Light>();
        }
        return this.light;
    }

    /**
     * Gets the value of the mesh property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mesh property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMesh().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Mesh }
     * 
     * 
     */
    public List<Mesh> getMesh() {
        if (mesh == null) {
            mesh = new ArrayList<Mesh>();
        }
        return this.mesh;
    }

    /**
     * Gets the value of the skinnedMesh property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the skinnedMesh property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSkinnedMesh().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SkinnedMesh }
     * 
     * 
     */
    public List<SkinnedMesh> getSkinnedMesh() {
        if (skinnedMesh == null) {
            skinnedMesh = new ArrayList<SkinnedMesh>();
        }
        return this.skinnedMesh;
    }

    /**
     * Gets the value of the group property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the group property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Group }
     * 
     * 
     */
    public List<Group> getGroup() {
        if (group == null) {
            group = new ArrayList<Group>();
        }
        return this.group;
    }

}
