//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 06:07:01 PM EST 
//


package m3x.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImageBaseColorType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ImageBaseColorType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ALPHA"/>
 *     &lt;enumeration value="LUMINANCE"/>
 *     &lt;enumeration value="LUMINANCE_ALPHA"/>
 *     &lt;enumeration value="RGB"/>
 *     &lt;enumeration value="RGB_ETC"/>
 *     &lt;enumeration value="RGB565"/>
 *     &lt;enumeration value="RGB565"/>
 *     &lt;enumeration value="RGBA"/>
 *     &lt;enumeration value="RGBA4444"/>
 *     &lt;enumeration value="RGBA5551"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ImageBaseColorType")
@XmlEnum
public enum ImageBaseColorType {

    ALPHA("ALPHA"),
    LUMINANCE("LUMINANCE"),
    LUMINANCE_ALPHA("LUMINANCE_ALPHA"),
    RGB("RGB"),
    RGB_ETC("RGB_ETC"),
    @XmlEnumValue("RGB565")
    RGB_565("RGB565"),
    RGBA("RGBA"),
    @XmlEnumValue("RGBA4444")
    RGBA_4444("RGBA4444"),
    @XmlEnumValue("RGBA5551")
    RGBA_5551("RGBA5551");
    private final String value;

    ImageBaseColorType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ImageBaseColorType fromValue(String v) {
        for (ImageBaseColorType c: ImageBaseColorType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
