//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 06:07:01 PM EST 
//


package m3x.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}ImageBaseType">
 *       &lt;sequence>
 *         &lt;element ref="{}palette" minOccurs="0"/>
 *         &lt;element ref="{}pixels" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "palette",
    "pixels"
})
@XmlRootElement(name = "Image2D")
public class Image2D
    extends ImageBaseType
{

    @XmlList
    @XmlElement(type = Short.class)
    protected List<Short> palette;
    @XmlList
    @XmlElement(type = Short.class)
    protected List<Short> pixels;

    /**
     * Gets the value of the palette property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the palette property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPalette().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Short }
     * 
     * 
     */
    public List<Short> getPalette() {
        if (palette == null) {
            palette = new ArrayList<Short>();
        }
        return this.palette;
    }

    /**
     * Gets the value of the pixels property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pixels property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPixels().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Short }
     * 
     * 
     */
    public List<Short> getPixels() {
        if (pixels == null) {
            pixels = new ArrayList<Short>();
        }
        return this.pixels;
    }

}
