//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.02 at 11:04:04 PM EST 
//


package m3x.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImageBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImageBaseType">
 *   &lt;complexContent>
 *     &lt;extension base="{}Object3DType">
 *       &lt;attribute name="format" type="{}ImageBaseColorType" />
 *       &lt;attribute name="mutable" type="{}bool" />
 *       &lt;attribute name="width" type="{}uint" />
 *       &lt;attribute name="height" type="{}uint" />
 *       &lt;attribute name="mipmap" type="{}bool" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImageBaseType")
@XmlSeeAlso({
    Image2D.class
})
public class ImageBaseType
    extends Object3DType
{

    @XmlAttribute
    protected ImageBaseColorType format;
    @XmlAttribute
    protected Boolean mutable;
    @XmlAttribute
    protected BigInteger width;
    @XmlAttribute
    protected BigInteger height;
    @XmlAttribute
    protected Boolean mipmap;

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link ImageBaseColorType }
     *     
     */
    public ImageBaseColorType getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageBaseColorType }
     *     
     */
    public void setFormat(ImageBaseColorType value) {
        this.format = value;
    }

    /**
     * Gets the value of the mutable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMutable() {
        return mutable;
    }

    /**
     * Sets the value of the mutable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMutable(Boolean value) {
        this.mutable = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWidth(BigInteger value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHeight(BigInteger value) {
        this.height = value;
    }

    /**
     * Gets the value of the mipmap property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMipmap() {
        return mipmap;
    }

    /**
     * Sets the value of the mipmap property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMipmap(Boolean value) {
        this.mipmap = value;
    }

}
