//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 06:17:17 PM EST 
//


package m3x.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KeyframeInterpolationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="KeyframeInterpolationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="LINEAR"/>
 *     &lt;enumeration value="SLERP"/>
 *     &lt;enumeration value="SPLINE"/>
 *     &lt;enumeration value="SQUAD"/>
 *     &lt;enumeration value="STEP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "KeyframeInterpolationType")
@XmlEnum
public enum KeyframeInterpolationType {

    LINEAR,
    SLERP,
    SPLINE,
    SQUAD,
    STEP;

    public String value() {
        return name();
    }

    public static KeyframeInterpolationType fromValue(String v) {
        return valueOf(v);
    }

}
