//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 08:26:55 PM EST 
//


package m3x.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}Object3DType">
 *       &lt;sequence>
 *         &lt;element ref="{}keytimes"/>
 *         &lt;element ref="{}keyframes"/>
 *       &lt;/sequence>
 *       &lt;attribute name="componentCount" type="{}UInt32" />
 *       &lt;attribute name="keyframeCount" type="{}UInt32" />
 *       &lt;attribute name="duration" type="{}UInt32" />
 *       &lt;attribute name="interpolation" type="{}KeyframeInterpolationType" />
 *       &lt;attribute name="validRangeFirst" type="{}UInt32" />
 *       &lt;attribute name="validRangeLast" type="{}UInt32" />
 *       &lt;attribute name="repeatMode" type="{}KeyframePlaybackType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "keytimes",
    "keyframes"
})
@XmlRootElement(name = "KeyframeSequence")
public class KeyframeSequence
    extends Object3DType
{

    @XmlList
    @XmlElement(type = Long.class)
    protected List<Long> keytimes;
    @XmlElement(required = true)
    protected Keyframes keyframes;
    @XmlAttribute
    protected Long componentCount;
    @XmlAttribute
    protected Long keyframeCount;
    @XmlAttribute
    protected Long duration;
    @XmlAttribute
    protected KeyframeInterpolationType interpolation;
    @XmlAttribute
    protected Long validRangeFirst;
    @XmlAttribute
    protected Long validRangeLast;
    @XmlAttribute
    protected KeyframePlaybackType repeatMode;

    /**
     * Gets the value of the keytimes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keytimes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeytimes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Long }
     * 
     * 
     */
    public List<Long> getKeytimes() {
        if (keytimes == null) {
            keytimes = new ArrayList<Long>();
        }
        return this.keytimes;
    }

    /**
     * Gets the value of the keyframes property.
     * 
     * @return
     *     possible object is
     *     {@link Keyframes }
     *     
     */
    public Keyframes getKeyframes() {
        return keyframes;
    }

    /**
     * Sets the value of the keyframes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Keyframes }
     *     
     */
    public void setKeyframes(Keyframes value) {
        this.keyframes = value;
    }

    /**
     * Gets the value of the componentCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getComponentCount() {
        return componentCount;
    }

    /**
     * Sets the value of the componentCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setComponentCount(Long value) {
        this.componentCount = value;
    }

    /**
     * Gets the value of the keyframeCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getKeyframeCount() {
        return keyframeCount;
    }

    /**
     * Sets the value of the keyframeCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setKeyframeCount(Long value) {
        this.keyframeCount = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDuration(Long value) {
        this.duration = value;
    }

    /**
     * Gets the value of the interpolation property.
     * 
     * @return
     *     possible object is
     *     {@link KeyframeInterpolationType }
     *     
     */
    public KeyframeInterpolationType getInterpolation() {
        return interpolation;
    }

    /**
     * Sets the value of the interpolation property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyframeInterpolationType }
     *     
     */
    public void setInterpolation(KeyframeInterpolationType value) {
        this.interpolation = value;
    }

    /**
     * Gets the value of the validRangeFirst property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getValidRangeFirst() {
        return validRangeFirst;
    }

    /**
     * Sets the value of the validRangeFirst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setValidRangeFirst(Long value) {
        this.validRangeFirst = value;
    }

    /**
     * Gets the value of the validRangeLast property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getValidRangeLast() {
        return validRangeLast;
    }

    /**
     * Sets the value of the validRangeLast property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setValidRangeLast(Long value) {
        this.validRangeLast = value;
    }

    /**
     * Gets the value of the repeatMode property.
     * 
     * @return
     *     possible object is
     *     {@link KeyframePlaybackType }
     *     
     */
    public KeyframePlaybackType getRepeatMode() {
        return repeatMode;
    }

    /**
     * Sets the value of the repeatMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyframePlaybackType }
     *     
     */
    public void setRepeatMode(KeyframePlaybackType value) {
        this.repeatMode = value;
    }

}
