//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 06:17:17 PM EST 
//


package m3x.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}NodeType">
 *       &lt;attribute name="attenuationConstant" type="{}Float32" />
 *       &lt;attribute name="attenuationLinear" type="{}Float32" />
 *       &lt;attribute name="attenuationQuadratic" type="{}Float32" />
 *       &lt;attribute name="color" type="{}ColorRGB" />
 *       &lt;attribute name="mode" type="{}LightType" />
 *       &lt;attribute name="intensity" type="{}Float32" />
 *       &lt;attribute name="spotAngle" type="{}Float32" />
 *       &lt;attribute name="spotExponent" type="{}Float32" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Light")
public class Light
    extends NodeType
{

    @XmlAttribute
    protected Float attenuationConstant;
    @XmlAttribute
    protected Float attenuationLinear;
    @XmlAttribute
    protected Float attenuationQuadratic;
    @XmlAttribute
    protected List<Short> color;
    @XmlAttribute
    protected LightType mode;
    @XmlAttribute
    protected Float intensity;
    @XmlAttribute
    protected Float spotAngle;
    @XmlAttribute
    protected Float spotExponent;

    /**
     * Gets the value of the attenuationConstant property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getAttenuationConstant() {
        return attenuationConstant;
    }

    /**
     * Sets the value of the attenuationConstant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAttenuationConstant(Float value) {
        this.attenuationConstant = value;
    }

    /**
     * Gets the value of the attenuationLinear property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getAttenuationLinear() {
        return attenuationLinear;
    }

    /**
     * Sets the value of the attenuationLinear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAttenuationLinear(Float value) {
        this.attenuationLinear = value;
    }

    /**
     * Gets the value of the attenuationQuadratic property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getAttenuationQuadratic() {
        return attenuationQuadratic;
    }

    /**
     * Sets the value of the attenuationQuadratic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAttenuationQuadratic(Float value) {
        this.attenuationQuadratic = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the color property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Short }
     * 
     * 
     */
    public List<Short> getColor() {
        if (color == null) {
            color = new ArrayList<Short>();
        }
        return this.color;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link LightType }
     *     
     */
    public LightType getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link LightType }
     *     
     */
    public void setMode(LightType value) {
        this.mode = value;
    }

    /**
     * Gets the value of the intensity property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getIntensity() {
        return intensity;
    }

    /**
     * Sets the value of the intensity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setIntensity(Float value) {
        this.intensity = value;
    }

    /**
     * Gets the value of the spotAngle property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSpotAngle() {
        return spotAngle;
    }

    /**
     * Sets the value of the spotAngle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSpotAngle(Float value) {
        this.spotAngle = value;
    }

    /**
     * Gets the value of the spotExponent property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSpotExponent() {
        return spotExponent;
    }

    /**
     * Sets the value of the spotExponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSpotExponent(Float value) {
        this.spotExponent = value;
    }

}
