//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 06:07:01 PM EST 
//


package m3x.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}Object3DType">
 *       &lt;attribute name="ambientColor" type="{}ColorRGB" />
 *       &lt;attribute name="diffuseColor" type="{}ColorRGBA" />
 *       &lt;attribute name="emissiveColor" type="{}ColorRGB" />
 *       &lt;attribute name="specularColor" type="{}ColorRGB" />
 *       &lt;attribute name="shininess" type="{}Float32" />
 *       &lt;attribute name="vertexColorTrackingEnabled" type="{}Boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Material")
public class Material
    extends Object3DType
{

    @XmlAttribute
    protected List<Short> ambientColor;
    @XmlAttribute
    protected List<Short> diffuseColor;
    @XmlAttribute
    protected List<Short> emissiveColor;
    @XmlAttribute
    protected List<Short> specularColor;
    @XmlAttribute
    protected Float shininess;
    @XmlAttribute
    protected Boolean vertexColorTrackingEnabled;

    /**
     * Gets the value of the ambientColor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ambientColor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAmbientColor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Short }
     * 
     * 
     */
    public List<Short> getAmbientColor() {
        if (ambientColor == null) {
            ambientColor = new ArrayList<Short>();
        }
        return this.ambientColor;
    }

    /**
     * Gets the value of the diffuseColor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the diffuseColor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiffuseColor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Short }
     * 
     * 
     */
    public List<Short> getDiffuseColor() {
        if (diffuseColor == null) {
            diffuseColor = new ArrayList<Short>();
        }
        return this.diffuseColor;
    }

    /**
     * Gets the value of the emissiveColor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the emissiveColor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmissiveColor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Short }
     * 
     * 
     */
    public List<Short> getEmissiveColor() {
        if (emissiveColor == null) {
            emissiveColor = new ArrayList<Short>();
        }
        return this.emissiveColor;
    }

    /**
     * Gets the value of the specularColor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specularColor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecularColor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Short }
     * 
     * 
     */
    public List<Short> getSpecularColor() {
        if (specularColor == null) {
            specularColor = new ArrayList<Short>();
        }
        return this.specularColor;
    }

    /**
     * Gets the value of the shininess property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getShininess() {
        return shininess;
    }

    /**
     * Sets the value of the shininess property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setShininess(Float value) {
        this.shininess = value;
    }

    /**
     * Gets the value of the vertexColorTrackingEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVertexColorTrackingEnabled() {
        return vertexColorTrackingEnabled;
    }

    /**
     * Sets the value of the vertexColorTrackingEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVertexColorTrackingEnabled(Boolean value) {
        this.vertexColorTrackingEnabled = value;
    }

}
