//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.02 at 11:04:04 PM EST 
//


package m3x.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}Object3DType">
 *       &lt;attribute name="ambient" type="{}int" />
 *       &lt;attribute name="diffuse" type="{}int" />
 *       &lt;attribute name="emissive" type="{}int" />
 *       &lt;attribute name="specular" type="{}int" />
 *       &lt;attribute name="shininess" type="{}float" />
 *       &lt;attribute name="vertexColor" type="{}bool" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Material")
public class Material
    extends Object3DType
{

    @XmlAttribute
    protected Long ambient;
    @XmlAttribute
    protected Long diffuse;
    @XmlAttribute
    protected Long emissive;
    @XmlAttribute
    protected Long specular;
    @XmlAttribute
    protected Double shininess;
    @XmlAttribute
    protected Boolean vertexColor;

    /**
     * Gets the value of the ambient property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAmbient() {
        return ambient;
    }

    /**
     * Sets the value of the ambient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAmbient(Long value) {
        this.ambient = value;
    }

    /**
     * Gets the value of the diffuse property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDiffuse() {
        return diffuse;
    }

    /**
     * Sets the value of the diffuse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDiffuse(Long value) {
        this.diffuse = value;
    }

    /**
     * Gets the value of the emissive property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getEmissive() {
        return emissive;
    }

    /**
     * Sets the value of the emissive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setEmissive(Long value) {
        this.emissive = value;
    }

    /**
     * Gets the value of the specular property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSpecular() {
        return specular;
    }

    /**
     * Sets the value of the specular property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSpecular(Long value) {
        this.specular = value;
    }

    /**
     * Gets the value of the shininess property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getShininess() {
        return shininess;
    }

    /**
     * Sets the value of the shininess property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setShininess(Double value) {
        this.shininess = value;
    }

    /**
     * Gets the value of the vertexColor property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVertexColor() {
        return vertexColor;
    }

    /**
     * Sets the value of the vertexColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVertexColor(Boolean value) {
        this.vertexColor = value;
    }

}
