//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 08:26:55 PM EST 
//


package m3x.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MeshType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeshType">
 *   &lt;complexContent>
 *     &lt;extension base="{}NodeType">
 *       &lt;sequence>
 *         &lt;element ref="{}VertexBufferInstance"/>
 *         &lt;element name="submesh" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}TriangleStripArrayInstance"/>
 *                   &lt;element ref="{}AppearanceInstance"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeshType", propOrder = {
    "vertexBufferInstance",
    "submesh"
})
@XmlSeeAlso({
    SkinnedMesh.class,
    Mesh.class,
    MorphingMesh.class
})
public class MeshType
    extends NodeType
{

    @XmlElement(name = "VertexBufferInstance", required = true)
    protected VertexBufferInstance vertexBufferInstance;
    @XmlElement(required = true)
    protected List<MeshType.Submesh> submesh;

    /**
     * Gets the value of the vertexBufferInstance property.
     * 
     * @return
     *     possible object is
     *     {@link VertexBufferInstance }
     *     
     */
    public VertexBufferInstance getVertexBufferInstance() {
        return vertexBufferInstance;
    }

    /**
     * Sets the value of the vertexBufferInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link VertexBufferInstance }
     *     
     */
    public void setVertexBufferInstance(VertexBufferInstance value) {
        this.vertexBufferInstance = value;
    }

    /**
     * Gets the value of the submesh property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the submesh property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubmesh().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeshType.Submesh }
     * 
     * 
     */
    public List<MeshType.Submesh> getSubmesh() {
        if (submesh == null) {
            submesh = new ArrayList<MeshType.Submesh>();
        }
        return this.submesh;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}TriangleStripArrayInstance"/>
     *         &lt;element ref="{}AppearanceInstance"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "triangleStripArrayInstance",
        "appearanceInstance"
    })
    public static class Submesh {

        @XmlElement(name = "TriangleStripArrayInstance", required = true)
        protected TriangleStripArrayInstance triangleStripArrayInstance;
        @XmlElement(name = "AppearanceInstance", required = true)
        protected AppearanceInstance appearanceInstance;

        /**
         * Gets the value of the triangleStripArrayInstance property.
         * 
         * @return
         *     possible object is
         *     {@link TriangleStripArrayInstance }
         *     
         */
        public TriangleStripArrayInstance getTriangleStripArrayInstance() {
            return triangleStripArrayInstance;
        }

        /**
         * Sets the value of the triangleStripArrayInstance property.
         * 
         * @param value
         *     allowed object is
         *     {@link TriangleStripArrayInstance }
         *     
         */
        public void setTriangleStripArrayInstance(TriangleStripArrayInstance value) {
            this.triangleStripArrayInstance = value;
        }

        /**
         * Gets the value of the appearanceInstance property.
         * 
         * @return
         *     possible object is
         *     {@link AppearanceInstance }
         *     
         */
        public AppearanceInstance getAppearanceInstance() {
            return appearanceInstance;
        }

        /**
         * Sets the value of the appearanceInstance property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppearanceInstance }
         *     
         */
        public void setAppearanceInstance(AppearanceInstance value) {
            this.appearanceInstance = value;
        }

    }

}
