//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 08:26:55 PM EST 
//


package m3x.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}MeshType">
 *       &lt;sequence>
 *         &lt;element name="morphtarget" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}VertexBufferInstance"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="weight" type="{}Float32" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "morphtarget"
})
@XmlRootElement(name = "MorphingMesh")
public class MorphingMesh
    extends MeshType
{

    @XmlElement(required = true)
    protected List<MorphingMesh.Morphtarget> morphtarget;

    /**
     * Gets the value of the morphtarget property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the morphtarget property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMorphtarget().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MorphingMesh.Morphtarget }
     * 
     * 
     */
    public List<MorphingMesh.Morphtarget> getMorphtarget() {
        if (morphtarget == null) {
            morphtarget = new ArrayList<MorphingMesh.Morphtarget>();
        }
        return this.morphtarget;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}VertexBufferInstance"/>
     *       &lt;/sequence>
     *       &lt;attribute name="weight" type="{}Float32" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vertexBufferInstance"
    })
    public static class Morphtarget {

        @XmlElement(name = "VertexBufferInstance", required = true)
        protected VertexBufferInstance vertexBufferInstance;
        @XmlAttribute
        protected Float weight;

        /**
         * Gets the value of the vertexBufferInstance property.
         * 
         * @return
         *     possible object is
         *     {@link VertexBufferInstance }
         *     
         */
        public VertexBufferInstance getVertexBufferInstance() {
            return vertexBufferInstance;
        }

        /**
         * Sets the value of the vertexBufferInstance property.
         * 
         * @param value
         *     allowed object is
         *     {@link VertexBufferInstance }
         *     
         */
        public void setVertexBufferInstance(VertexBufferInstance value) {
            this.vertexBufferInstance = value;
        }

        /**
         * Gets the value of the weight property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getWeight() {
            return weight;
        }

        /**
         * Sets the value of the weight property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setWeight(Float value) {
            this.weight = value;
        }

    }

}
