//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 06:07:01 PM EST 
//


package m3x.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NodeType">
 *   &lt;complexContent>
 *     &lt;extension base="{}TransformableType">
 *       &lt;attribute name="renderingEnabled" type="{}Boolean" default="true" />
 *       &lt;attribute name="pickingEnabled" type="{}Boolean" default="true" />
 *       &lt;attribute name="alphaFactor" type="{}Float32" default="1.0" />
 *       &lt;attribute name="scope" type="{}Int32" default="-1" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NodeType")
@XmlSeeAlso({
    Light.class,
    GroupType.class,
    Camera.class,
    MeshType.class
})
public class NodeType
    extends TransformableType
{

    @XmlAttribute
    protected Boolean renderingEnabled;
    @XmlAttribute
    protected Boolean pickingEnabled;
    @XmlAttribute
    protected Float alphaFactor;
    @XmlAttribute
    protected Integer scope;

    /**
     * Gets the value of the renderingEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRenderingEnabled() {
        if (renderingEnabled == null) {
            return true;
        } else {
            return renderingEnabled;
        }
    }

    /**
     * Sets the value of the renderingEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRenderingEnabled(Boolean value) {
        this.renderingEnabled = value;
    }

    /**
     * Gets the value of the pickingEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPickingEnabled() {
        if (pickingEnabled == null) {
            return true;
        } else {
            return pickingEnabled;
        }
    }

    /**
     * Sets the value of the pickingEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPickingEnabled(Boolean value) {
        this.pickingEnabled = value;
    }

    /**
     * Gets the value of the alphaFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getAlphaFactor() {
        if (alphaFactor == null) {
            return  1.0F;
        } else {
            return alphaFactor;
        }
    }

    /**
     * Sets the value of the alphaFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAlphaFactor(Float value) {
        this.alphaFactor = value;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getScope() {
        if (scope == null) {
            return -1;
        } else {
            return scope;
        }
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setScope(Integer value) {
        this.scope = value;
    }

}
