//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.02 at 11:04:04 PM EST 
//


package m3x.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NodeType">
 *   &lt;complexContent>
 *     &lt;extension base="{}TransformableType">
 *       &lt;attribute name="rendering" type="{}bool" default="true" />
 *       &lt;attribute name="picking" type="{}bool" default="true" />
 *       &lt;attribute name="alphaFactor" type="{}float" default="1.0" />
 *       &lt;attribute name="scope" type="{}int" default="-1" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NodeType")
@XmlSeeAlso({
    MeshType.class,
    Light.class,
    GroupType.class,
    Camera.class
})
public class NodeType
    extends TransformableType
{

    @XmlAttribute
    protected Boolean rendering;
    @XmlAttribute
    protected Boolean picking;
    @XmlAttribute
    protected Double alphaFactor;
    @XmlAttribute
    protected Long scope;

    /**
     * Gets the value of the rendering property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRendering() {
        if (rendering == null) {
            return true;
        } else {
            return rendering;
        }
    }

    /**
     * Sets the value of the rendering property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRendering(Boolean value) {
        this.rendering = value;
    }

    /**
     * Gets the value of the picking property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPicking() {
        if (picking == null) {
            return true;
        } else {
            return picking;
        }
    }

    /**
     * Sets the value of the picking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPicking(Boolean value) {
        this.picking = value;
    }

    /**
     * Gets the value of the alphaFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getAlphaFactor() {
        if (alphaFactor == null) {
            return  1.0D;
        } else {
            return alphaFactor;
        }
    }

    /**
     * Sets the value of the alphaFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAlphaFactor(Double value) {
        this.alphaFactor = value;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getScope() {
        if (scope == null) {
            return -1L;
        } else {
            return scope;
        }
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setScope(Long value) {
        this.scope = value;
    }

}
