//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 06:07:01 PM EST 
//


package m3x.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NodeAlignmentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NodeAlignmentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NONE"/>
 *     &lt;enumeration value="ORIGIN"/>
 *     &lt;enumeration value="X_AXIS"/>
 *     &lt;enumeration value="Y_AXIS"/>
 *     &lt;enumeration value="Z_AXIS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NodeAlignmentType")
@XmlEnum
public enum NodeAlignmentType {

    NONE,
    ORIGIN,
    X_AXIS,
    Y_AXIS,
    Z_AXIS;

    public String value() {
        return name();
    }

    public static NodeAlignmentType fromValue(String v) {
        return valueOf(v);
    }

}
