//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.02 at 11:04:04 PM EST 
//


package m3x.jaxb;

import java.math.BigInteger;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the m3x.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Palette_QNAME = new QName("", "palette");
    private final static QName _IntArray_QNAME = new QName("", "int_array");
    private final static QName _Transform_QNAME = new QName("", "Transform");
    private final static QName _Keytimes_QNAME = new QName("", "keytimes");
    private final static QName _Pixels_QNAME = new QName("", "pixels");
    private final static QName _ProjectionTransform_QNAME = new QName("", "ProjectionTransform");
    private final static QName _Lengths_QNAME = new QName("", "lengths");
    private final static QName _Scale_QNAME = new QName("", "scale");
    private final static QName _Translate_QNAME = new QName("", "translate");
    private final static QName _FloatArray_QNAME = new QName("", "float_array");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: m3x.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AnimationController }
     * 
     */
    public AnimationController createAnimationController() {
        return new AnimationController();
    }

    /**
     * Create an instance of {@link FogInstance }
     * 
     */
    public FogInstance createFogInstance() {
        return new FogInstance();
    }

    /**
     * Create an instance of {@link Image2D }
     * 
     */
    public Image2D createImage2D() {
        return new Image2D();
    }

    /**
     * Create an instance of {@link VertexBuffer.Positions }
     * 
     */
    public VertexBuffer.Positions createVertexBufferPositions() {
        return new VertexBuffer.Positions();
    }

    /**
     * Create an instance of {@link Light }
     * 
     */
    public Light createLight() {
        return new Light();
    }

    /**
     * Create an instance of {@link Background }
     * 
     */
    public Background createBackground() {
        return new Background();
    }

    /**
     * Create an instance of {@link VertexArray }
     * 
     */
    public VertexArray createVertexArray() {
        return new VertexArray();
    }

    /**
     * Create an instance of {@link VertexBuffer }
     * 
     */
    public VertexBuffer createVertexBuffer() {
        return new VertexBuffer();
    }

    /**
     * Create an instance of {@link M3G }
     * 
     */
    public M3G createM3G() {
        return new M3G();
    }

    /**
     * Create an instance of {@link AnimationControllerInstance }
     * 
     */
    public AnimationControllerInstance createAnimationControllerInstance() {
        return new AnimationControllerInstance();
    }

    /**
     * Create an instance of {@link GroupType }
     * 
     */
    public GroupType createGroupType() {
        return new GroupType();
    }

    /**
     * Create an instance of {@link Fog }
     * 
     */
    public Fog createFog() {
        return new Fog();
    }

    /**
     * Create an instance of {@link World }
     * 
     */
    public World createWorld() {
        return new World();
    }

    /**
     * Create an instance of {@link MeshType.Submesh }
     * 
     */
    public MeshType.Submesh createMeshTypeSubmesh() {
        return new MeshType.Submesh();
    }

    /**
     * Create an instance of {@link Texture2D }
     * 
     */
    public Texture2D createTexture2D() {
        return new Texture2D();
    }

    /**
     * Create an instance of {@link PolygonModeInstance }
     * 
     */
    public PolygonModeInstance createPolygonModeInstance() {
        return new PolygonModeInstance();
    }

    /**
     * Create an instance of {@link SkinnedMesh.Bone }
     * 
     */
    public SkinnedMesh.Bone createSkinnedMeshBone() {
        return new SkinnedMesh.Bone();
    }

    /**
     * Create an instance of {@link IndexBufferType }
     * 
     */
    public IndexBufferType createIndexBufferType() {
        return new IndexBufferType();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link TriangleStripArrayInstance }
     * 
     */
    public TriangleStripArrayInstance createTriangleStripArrayInstance() {
        return new TriangleStripArrayInstance();
    }

    /**
     * Create an instance of {@link CompositingMode }
     * 
     */
    public CompositingMode createCompositingMode() {
        return new CompositingMode();
    }

    /**
     * Create an instance of {@link Texture2DInstance }
     * 
     */
    public Texture2DInstance createTexture2DInstance() {
        return new Texture2DInstance();
    }

    /**
     * Create an instance of {@link AnimationTrack }
     * 
     */
    public AnimationTrack createAnimationTrack() {
        return new AnimationTrack();
    }

    /**
     * Create an instance of {@link Material }
     * 
     */
    public Material createMaterial() {
        return new Material();
    }

    /**
     * Create an instance of {@link KeyframeSequence }
     * 
     */
    public KeyframeSequence createKeyframeSequence() {
        return new KeyframeSequence();
    }

    /**
     * Create an instance of {@link ImageBaseType }
     * 
     */
    public ImageBaseType createImageBaseType() {
        return new ImageBaseType();
    }

    /**
     * Create an instance of {@link NodeType }
     * 
     */
    public NodeType createNodeType() {
        return new NodeType();
    }

    /**
     * Create an instance of {@link VertexBufferInstance }
     * 
     */
    public VertexBufferInstance createVertexBufferInstance() {
        return new VertexBufferInstance();
    }

    /**
     * Create an instance of {@link VertexBuffer.Colors }
     * 
     */
    public VertexBuffer.Colors createVertexBufferColors() {
        return new VertexBuffer.Colors();
    }

    /**
     * Create an instance of {@link Mesh }
     * 
     */
    public Mesh createMesh() {
        return new Mesh();
    }

    /**
     * Create an instance of {@link CompositingModeInstance }
     * 
     */
    public CompositingModeInstance createCompositingModeInstance() {
        return new CompositingModeInstance();
    }

    /**
     * Create an instance of {@link AppearanceInstance }
     * 
     */
    public AppearanceInstance createAppearanceInstance() {
        return new AppearanceInstance();
    }

    /**
     * Create an instance of {@link PolygonMode }
     * 
     */
    public PolygonMode createPolygonMode() {
        return new PolygonMode();
    }

    /**
     * Create an instance of {@link MorphingMesh.Morphtarget }
     * 
     */
    public MorphingMesh.Morphtarget createMorphingMeshMorphtarget() {
        return new MorphingMesh.Morphtarget();
    }

    /**
     * Create an instance of {@link Appearance }
     * 
     */
    public Appearance createAppearance() {
        return new Appearance();
    }

    /**
     * Create an instance of {@link ImageBaseInstance }
     * 
     */
    public ImageBaseInstance createImageBaseInstance() {
        return new ImageBaseInstance();
    }

    /**
     * Create an instance of {@link VertexBuffer.Texcoords }
     * 
     */
    public VertexBuffer.Texcoords createVertexBufferTexcoords() {
        return new VertexBuffer.Texcoords();
    }

    /**
     * Create an instance of {@link KeyframeSequenceInstance }
     * 
     */
    public KeyframeSequenceInstance createKeyframeSequenceInstance() {
        return new KeyframeSequenceInstance();
    }

    /**
     * Create an instance of {@link InstanceType }
     * 
     */
    public InstanceType createInstanceType() {
        return new InstanceType();
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link TriangleStripArray }
     * 
     */
    public TriangleStripArray createTriangleStripArray() {
        return new TriangleStripArray();
    }

    /**
     * Create an instance of {@link Image2DInstance }
     * 
     */
    public Image2DInstance createImage2DInstance() {
        return new Image2DInstance();
    }

    /**
     * Create an instance of {@link MeshType }
     * 
     */
    public MeshType createMeshType() {
        return new MeshType();
    }

    /**
     * Create an instance of {@link VertexArrayInstance }
     * 
     */
    public VertexArrayInstance createVertexArrayInstance() {
        return new VertexArrayInstance();
    }

    /**
     * Create an instance of {@link MaterialInstance }
     * 
     */
    public MaterialInstance createMaterialInstance() {
        return new MaterialInstance();
    }

    /**
     * Create an instance of {@link IndexBufferInstance }
     * 
     */
    public IndexBufferInstance createIndexBufferInstance() {
        return new IndexBufferInstance();
    }

    /**
     * Create an instance of {@link SkinnedMesh }
     * 
     */
    public SkinnedMesh createSkinnedMesh() {
        return new SkinnedMesh();
    }

    /**
     * Create an instance of {@link Keyframes }
     * 
     */
    public Keyframes createKeyframes() {
        return new Keyframes();
    }

    /**
     * Create an instance of {@link VertexBuffer.Normals }
     * 
     */
    public VertexBuffer.Normals createVertexBufferNormals() {
        return new VertexBuffer.Normals();
    }

    /**
     * Create an instance of {@link TransformableType }
     * 
     */
    public TransformableType createTransformableType() {
        return new TransformableType();
    }

    /**
     * Create an instance of {@link Camera }
     * 
     */
    public Camera createCamera() {
        return new Camera();
    }

    /**
     * Create an instance of {@link Rotate }
     * 
     */
    public Rotate createRotate() {
        return new Rotate();
    }

    /**
     * Create an instance of {@link AnimationTrackInstance }
     * 
     */
    public AnimationTrackInstance createAnimationTrackInstance() {
        return new AnimationTrackInstance();
    }

    /**
     * Create an instance of {@link MorphingMesh }
     * 
     */
    public MorphingMesh createMorphingMesh() {
        return new MorphingMesh();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link BigInteger }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "palette")
    public JAXBElement<List<BigInteger>> createPalette(List<BigInteger> value) {
        return new JAXBElement<List<BigInteger>>(_Palette_QNAME, ((Class) List.class), null, ((List<BigInteger> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link Long }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "int_array")
    public JAXBElement<List<Long>> createIntArray(List<Long> value) {
        return new JAXBElement<List<Long>>(_IntArray_QNAME, ((Class) List.class), null, ((List<Long> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link Double }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Transform")
    public JAXBElement<List<Double>> createTransform(List<Double> value) {
        return new JAXBElement<List<Double>>(_Transform_QNAME, ((Class) List.class), null, ((List<Double> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link BigInteger }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "keytimes")
    public JAXBElement<List<BigInteger>> createKeytimes(List<BigInteger> value) {
        return new JAXBElement<List<BigInteger>>(_Keytimes_QNAME, ((Class) List.class), null, ((List<BigInteger> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link BigInteger }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pixels")
    public JAXBElement<List<BigInteger>> createPixels(List<BigInteger> value) {
        return new JAXBElement<List<BigInteger>>(_Pixels_QNAME, ((Class) List.class), null, ((List<BigInteger> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link Double }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProjectionTransform")
    public JAXBElement<List<Double>> createProjectionTransform(List<Double> value) {
        return new JAXBElement<List<Double>>(_ProjectionTransform_QNAME, ((Class) List.class), null, ((List<Double> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link BigInteger }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lengths")
    public JAXBElement<List<BigInteger>> createLengths(List<BigInteger> value) {
        return new JAXBElement<List<BigInteger>>(_Lengths_QNAME, ((Class) List.class), null, ((List<BigInteger> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link Double }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "scale")
    public JAXBElement<List<Double>> createScale(List<Double> value) {
        return new JAXBElement<List<Double>>(_Scale_QNAME, ((Class) List.class), null, ((List<Double> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link Double }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "translate")
    public JAXBElement<List<Double>> createTranslate(List<Double> value) {
        return new JAXBElement<List<Double>>(_Translate_QNAME, ((Class) List.class), null, ((List<Double> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link Double }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "float_array")
    public JAXBElement<List<Double>> createFloatArray(List<Double> value) {
        return new JAXBElement<List<Double>>(_FloatArray_QNAME, ((Class) List.class), null, ((List<Double> ) value));
    }

}
