//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 06:07:01 PM EST 
//


package m3x.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 *                 The Object3D type declares the basic storage of a serializable object for an M3G file.
 *             
 * 
 * <p>Java class for Object3DType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Object3DType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{}AnimationTrack"/>
 *           &lt;element ref="{}AnimationTrackInstance"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="userID" type="{}UInt32" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Object3DType", propOrder = {
    "animationTrack",
    "animationTrackInstance"
})
@XmlSeeAlso({
    Material.class,
    VertexArray.class,
    Background.class,
    Appearance.class,
    Fog.class,
    VertexBuffer.class,
    KeyframeSequence.class,
    IndexBufferType.class,
    CompositingMode.class,
    PolygonMode.class,
    ImageBaseType.class,
    AnimationController.class,
    TransformableType.class,
    AnimationTrack.class
})
public abstract class Object3DType {

    @XmlElement(name = "AnimationTrack")
    protected AnimationTrack animationTrack;
    @XmlElement(name = "AnimationTrackInstance")
    protected AnimationTrackInstance animationTrackInstance;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String name;
    @XmlAttribute
    protected Long userID;

    /**
     * 
     *                             An object can have any number of animation tracks targeting it.
     *                         
     * 
     * @return
     *     possible object is
     *     {@link AnimationTrack }
     *     
     */
    public AnimationTrack getAnimationTrack() {
        return animationTrack;
    }

    /**
     * Sets the value of the animationTrack property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnimationTrack }
     *     
     */
    public void setAnimationTrack(AnimationTrack value) {
        this.animationTrack = value;
    }

    /**
     * 
     *                             An object can have any number of animation tracks targeting it.
     *                         
     * 
     * @return
     *     possible object is
     *     {@link AnimationTrackInstance }
     *     
     */
    public AnimationTrackInstance getAnimationTrackInstance() {
        return animationTrackInstance;
    }

    /**
     * Sets the value of the animationTrackInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnimationTrackInstance }
     *     
     */
    public void setAnimationTrackInstance(AnimationTrackInstance value) {
        this.animationTrackInstance = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the userID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getUserID() {
        if (userID == null) {
            return  0L;
        } else {
            return userID;
        }
    }

    /**
     * Sets the value of the userID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUserID(Long value) {
        this.userID = value;
    }

}
