//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 06:17:17 PM EST 
//


package m3x.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}Object3DType">
 *       &lt;attribute name="culling" type="{}PolygonCullingModeType" />
 *       &lt;attribute name="shading" type="{}PolygonShadingModeType" />
 *       &lt;attribute name="winding" type="{}PolygonWindingModeType" />
 *       &lt;attribute name="twoSidedLightingEnabled" type="{}Boolean" />
 *       &lt;attribute name="localCameraLightingEnabled" type="{}Boolean" />
 *       &lt;attribute name="perspectiveCorrectionEnabled" type="{}Boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "PolygonMode")
public class PolygonMode
    extends Object3DType
{

    @XmlAttribute
    protected PolygonCullingModeType culling;
    @XmlAttribute
    protected PolygonShadingModeType shading;
    @XmlAttribute
    protected PolygonWindingModeType winding;
    @XmlAttribute
    protected Boolean twoSidedLightingEnabled;
    @XmlAttribute
    protected Boolean localCameraLightingEnabled;
    @XmlAttribute
    protected Boolean perspectiveCorrectionEnabled;

    /**
     * Gets the value of the culling property.
     * 
     * @return
     *     possible object is
     *     {@link PolygonCullingModeType }
     *     
     */
    public PolygonCullingModeType getCulling() {
        return culling;
    }

    /**
     * Sets the value of the culling property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolygonCullingModeType }
     *     
     */
    public void setCulling(PolygonCullingModeType value) {
        this.culling = value;
    }

    /**
     * Gets the value of the shading property.
     * 
     * @return
     *     possible object is
     *     {@link PolygonShadingModeType }
     *     
     */
    public PolygonShadingModeType getShading() {
        return shading;
    }

    /**
     * Sets the value of the shading property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolygonShadingModeType }
     *     
     */
    public void setShading(PolygonShadingModeType value) {
        this.shading = value;
    }

    /**
     * Gets the value of the winding property.
     * 
     * @return
     *     possible object is
     *     {@link PolygonWindingModeType }
     *     
     */
    public PolygonWindingModeType getWinding() {
        return winding;
    }

    /**
     * Sets the value of the winding property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolygonWindingModeType }
     *     
     */
    public void setWinding(PolygonWindingModeType value) {
        this.winding = value;
    }

    /**
     * Gets the value of the twoSidedLightingEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTwoSidedLightingEnabled() {
        return twoSidedLightingEnabled;
    }

    /**
     * Sets the value of the twoSidedLightingEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTwoSidedLightingEnabled(Boolean value) {
        this.twoSidedLightingEnabled = value;
    }

    /**
     * Gets the value of the localCameraLightingEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLocalCameraLightingEnabled() {
        return localCameraLightingEnabled;
    }

    /**
     * Sets the value of the localCameraLightingEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLocalCameraLightingEnabled(Boolean value) {
        this.localCameraLightingEnabled = value;
    }

    /**
     * Gets the value of the perspectiveCorrectionEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPerspectiveCorrectionEnabled() {
        return perspectiveCorrectionEnabled;
    }

    /**
     * Sets the value of the perspectiveCorrectionEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPerspectiveCorrectionEnabled(Boolean value) {
        this.perspectiveCorrectionEnabled = value;
    }

}
