//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.02 at 11:04:04 PM EST 
//


package m3x.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}Object3DType">
 *       &lt;attribute name="culling" type="{}PolygonCullingModeType" />
 *       &lt;attribute name="shading" type="{}PolygonShadingModeType" />
 *       &lt;attribute name="winding" type="{}PolygonWindingModeType" />
 *       &lt;attribute name="twoSidedLighting" type="{}bool" />
 *       &lt;attribute name="localCameraLighting" type="{}bool" />
 *       &lt;attribute name="perpectiveCorrection" type="{}bool" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "PolygonMode")
public class PolygonMode
    extends Object3DType
{

    @XmlAttribute
    protected PolygonCullingModeType culling;
    @XmlAttribute
    protected PolygonShadingModeType shading;
    @XmlAttribute
    protected PolygonWindingModeType winding;
    @XmlAttribute
    protected Boolean twoSidedLighting;
    @XmlAttribute
    protected Boolean localCameraLighting;
    @XmlAttribute
    protected Boolean perpectiveCorrection;

    /**
     * Gets the value of the culling property.
     * 
     * @return
     *     possible object is
     *     {@link PolygonCullingModeType }
     *     
     */
    public PolygonCullingModeType getCulling() {
        return culling;
    }

    /**
     * Sets the value of the culling property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolygonCullingModeType }
     *     
     */
    public void setCulling(PolygonCullingModeType value) {
        this.culling = value;
    }

    /**
     * Gets the value of the shading property.
     * 
     * @return
     *     possible object is
     *     {@link PolygonShadingModeType }
     *     
     */
    public PolygonShadingModeType getShading() {
        return shading;
    }

    /**
     * Sets the value of the shading property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolygonShadingModeType }
     *     
     */
    public void setShading(PolygonShadingModeType value) {
        this.shading = value;
    }

    /**
     * Gets the value of the winding property.
     * 
     * @return
     *     possible object is
     *     {@link PolygonWindingModeType }
     *     
     */
    public PolygonWindingModeType getWinding() {
        return winding;
    }

    /**
     * Sets the value of the winding property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolygonWindingModeType }
     *     
     */
    public void setWinding(PolygonWindingModeType value) {
        this.winding = value;
    }

    /**
     * Gets the value of the twoSidedLighting property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTwoSidedLighting() {
        return twoSidedLighting;
    }

    /**
     * Sets the value of the twoSidedLighting property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTwoSidedLighting(Boolean value) {
        this.twoSidedLighting = value;
    }

    /**
     * Gets the value of the localCameraLighting property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLocalCameraLighting() {
        return localCameraLighting;
    }

    /**
     * Sets the value of the localCameraLighting property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLocalCameraLighting(Boolean value) {
        this.localCameraLighting = value;
    }

    /**
     * Gets the value of the perpectiveCorrection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPerpectiveCorrection() {
        return perpectiveCorrection;
    }

    /**
     * Sets the value of the perpectiveCorrection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPerpectiveCorrection(Boolean value) {
        this.perpectiveCorrection = value;
    }

}
