//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.02 at 11:04:04 PM EST 
//


package m3x.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{}AnimationController"/>
 *           &lt;element ref="{}AnimationTrack"/>
 *           &lt;element ref="{}Appearance"/>
 *           &lt;element ref="{}Background"/>
 *           &lt;element ref="{}Camera"/>
 *           &lt;element ref="{}CompositingMode"/>
 *           &lt;element ref="{}Fog"/>
 *           &lt;element ref="{}Group"/>
 *           &lt;element ref="{}Image2D"/>
 *           &lt;element ref="{}KeyframeSequence"/>
 *           &lt;element ref="{}Light"/>
 *           &lt;element ref="{}Material"/>
 *           &lt;element ref="{}Mesh"/>
 *           &lt;element ref="{}MorphingMesh"/>
 *           &lt;element ref="{}PolygonMode"/>
 *           &lt;element ref="{}SkinnedMesh"/>
 *           &lt;element ref="{}Texture2D"/>
 *           &lt;element ref="{}TriangleStripArray"/>
 *           &lt;element ref="{}VertexArray"/>
 *           &lt;element ref="{}VertexBuffer"/>
 *           &lt;element ref="{}World"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "animationController",
    "animationTrack",
    "appearance",
    "background",
    "camera",
    "compositingMode",
    "fog",
    "group",
    "image2D",
    "keyframeSequence",
    "light",
    "material",
    "mesh",
    "morphingMesh",
    "polygonMode",
    "skinnedMesh",
    "texture2D",
    "triangleStripArray",
    "vertexArray",
    "vertexBuffer",
    "world"
})
@XmlRootElement(name = "section")
public class Section {

    @XmlElement(name = "AnimationController")
    protected AnimationController animationController;
    @XmlElement(name = "AnimationTrack")
    protected AnimationTrack animationTrack;
    @XmlElement(name = "Appearance")
    protected Appearance appearance;
    @XmlElement(name = "Background")
    protected Background background;
    @XmlElement(name = "Camera")
    protected Camera camera;
    @XmlElement(name = "CompositingMode")
    protected CompositingMode compositingMode;
    @XmlElement(name = "Fog")
    protected Fog fog;
    @XmlElement(name = "Group")
    protected Group group;
    @XmlElement(name = "Image2D")
    protected Image2D image2D;
    @XmlElement(name = "KeyframeSequence")
    protected KeyframeSequence keyframeSequence;
    @XmlElement(name = "Light")
    protected Light light;
    @XmlElement(name = "Material")
    protected Material material;
    @XmlElement(name = "Mesh")
    protected Mesh mesh;
    @XmlElement(name = "MorphingMesh")
    protected MorphingMesh morphingMesh;
    @XmlElement(name = "PolygonMode")
    protected PolygonMode polygonMode;
    @XmlElement(name = "SkinnedMesh")
    protected SkinnedMesh skinnedMesh;
    @XmlElement(name = "Texture2D")
    protected Texture2D texture2D;
    @XmlElement(name = "TriangleStripArray")
    protected TriangleStripArray triangleStripArray;
    @XmlElement(name = "VertexArray")
    protected VertexArray vertexArray;
    @XmlElement(name = "VertexBuffer")
    protected VertexBuffer vertexBuffer;
    @XmlElement(name = "World")
    protected World world;

    /**
     * Gets the value of the animationController property.
     * 
     * @return
     *     possible object is
     *     {@link AnimationController }
     *     
     */
    public AnimationController getAnimationController() {
        return animationController;
    }

    /**
     * Sets the value of the animationController property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnimationController }
     *     
     */
    public void setAnimationController(AnimationController value) {
        this.animationController = value;
    }

    /**
     * Gets the value of the animationTrack property.
     * 
     * @return
     *     possible object is
     *     {@link AnimationTrack }
     *     
     */
    public AnimationTrack getAnimationTrack() {
        return animationTrack;
    }

    /**
     * Sets the value of the animationTrack property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnimationTrack }
     *     
     */
    public void setAnimationTrack(AnimationTrack value) {
        this.animationTrack = value;
    }

    /**
     * Gets the value of the appearance property.
     * 
     * @return
     *     possible object is
     *     {@link Appearance }
     *     
     */
    public Appearance getAppearance() {
        return appearance;
    }

    /**
     * Sets the value of the appearance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Appearance }
     *     
     */
    public void setAppearance(Appearance value) {
        this.appearance = value;
    }

    /**
     * Gets the value of the background property.
     * 
     * @return
     *     possible object is
     *     {@link Background }
     *     
     */
    public Background getBackground() {
        return background;
    }

    /**
     * Sets the value of the background property.
     * 
     * @param value
     *     allowed object is
     *     {@link Background }
     *     
     */
    public void setBackground(Background value) {
        this.background = value;
    }

    /**
     * Gets the value of the camera property.
     * 
     * @return
     *     possible object is
     *     {@link Camera }
     *     
     */
    public Camera getCamera() {
        return camera;
    }

    /**
     * Sets the value of the camera property.
     * 
     * @param value
     *     allowed object is
     *     {@link Camera }
     *     
     */
    public void setCamera(Camera value) {
        this.camera = value;
    }

    /**
     * Gets the value of the compositingMode property.
     * 
     * @return
     *     possible object is
     *     {@link CompositingMode }
     *     
     */
    public CompositingMode getCompositingMode() {
        return compositingMode;
    }

    /**
     * Sets the value of the compositingMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompositingMode }
     *     
     */
    public void setCompositingMode(CompositingMode value) {
        this.compositingMode = value;
    }

    /**
     * Gets the value of the fog property.
     * 
     * @return
     *     possible object is
     *     {@link Fog }
     *     
     */
    public Fog getFog() {
        return fog;
    }

    /**
     * Sets the value of the fog property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fog }
     *     
     */
    public void setFog(Fog value) {
        this.fog = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link Group }
     *     
     */
    public Group getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link Group }
     *     
     */
    public void setGroup(Group value) {
        this.group = value;
    }

    /**
     * Gets the value of the image2D property.
     * 
     * @return
     *     possible object is
     *     {@link Image2D }
     *     
     */
    public Image2D getImage2D() {
        return image2D;
    }

    /**
     * Sets the value of the image2D property.
     * 
     * @param value
     *     allowed object is
     *     {@link Image2D }
     *     
     */
    public void setImage2D(Image2D value) {
        this.image2D = value;
    }

    /**
     * Gets the value of the keyframeSequence property.
     * 
     * @return
     *     possible object is
     *     {@link KeyframeSequence }
     *     
     */
    public KeyframeSequence getKeyframeSequence() {
        return keyframeSequence;
    }

    /**
     * Sets the value of the keyframeSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyframeSequence }
     *     
     */
    public void setKeyframeSequence(KeyframeSequence value) {
        this.keyframeSequence = value;
    }

    /**
     * Gets the value of the light property.
     * 
     * @return
     *     possible object is
     *     {@link Light }
     *     
     */
    public Light getLight() {
        return light;
    }

    /**
     * Sets the value of the light property.
     * 
     * @param value
     *     allowed object is
     *     {@link Light }
     *     
     */
    public void setLight(Light value) {
        this.light = value;
    }

    /**
     * Gets the value of the material property.
     * 
     * @return
     *     possible object is
     *     {@link Material }
     *     
     */
    public Material getMaterial() {
        return material;
    }

    /**
     * Sets the value of the material property.
     * 
     * @param value
     *     allowed object is
     *     {@link Material }
     *     
     */
    public void setMaterial(Material value) {
        this.material = value;
    }

    /**
     * Gets the value of the mesh property.
     * 
     * @return
     *     possible object is
     *     {@link Mesh }
     *     
     */
    public Mesh getMesh() {
        return mesh;
    }

    /**
     * Sets the value of the mesh property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mesh }
     *     
     */
    public void setMesh(Mesh value) {
        this.mesh = value;
    }

    /**
     * Gets the value of the morphingMesh property.
     * 
     * @return
     *     possible object is
     *     {@link MorphingMesh }
     *     
     */
    public MorphingMesh getMorphingMesh() {
        return morphingMesh;
    }

    /**
     * Sets the value of the morphingMesh property.
     * 
     * @param value
     *     allowed object is
     *     {@link MorphingMesh }
     *     
     */
    public void setMorphingMesh(MorphingMesh value) {
        this.morphingMesh = value;
    }

    /**
     * Gets the value of the polygonMode property.
     * 
     * @return
     *     possible object is
     *     {@link PolygonMode }
     *     
     */
    public PolygonMode getPolygonMode() {
        return polygonMode;
    }

    /**
     * Sets the value of the polygonMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolygonMode }
     *     
     */
    public void setPolygonMode(PolygonMode value) {
        this.polygonMode = value;
    }

    /**
     * Gets the value of the skinnedMesh property.
     * 
     * @return
     *     possible object is
     *     {@link SkinnedMesh }
     *     
     */
    public SkinnedMesh getSkinnedMesh() {
        return skinnedMesh;
    }

    /**
     * Sets the value of the skinnedMesh property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkinnedMesh }
     *     
     */
    public void setSkinnedMesh(SkinnedMesh value) {
        this.skinnedMesh = value;
    }

    /**
     * Gets the value of the texture2D property.
     * 
     * @return
     *     possible object is
     *     {@link Texture2D }
     *     
     */
    public Texture2D getTexture2D() {
        return texture2D;
    }

    /**
     * Sets the value of the texture2D property.
     * 
     * @param value
     *     allowed object is
     *     {@link Texture2D }
     *     
     */
    public void setTexture2D(Texture2D value) {
        this.texture2D = value;
    }

    /**
     * Gets the value of the triangleStripArray property.
     * 
     * @return
     *     possible object is
     *     {@link TriangleStripArray }
     *     
     */
    public TriangleStripArray getTriangleStripArray() {
        return triangleStripArray;
    }

    /**
     * Sets the value of the triangleStripArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link TriangleStripArray }
     *     
     */
    public void setTriangleStripArray(TriangleStripArray value) {
        this.triangleStripArray = value;
    }

    /**
     * Gets the value of the vertexArray property.
     * 
     * @return
     *     possible object is
     *     {@link VertexArray }
     *     
     */
    public VertexArray getVertexArray() {
        return vertexArray;
    }

    /**
     * Sets the value of the vertexArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link VertexArray }
     *     
     */
    public void setVertexArray(VertexArray value) {
        this.vertexArray = value;
    }

    /**
     * Gets the value of the vertexBuffer property.
     * 
     * @return
     *     possible object is
     *     {@link VertexBuffer }
     *     
     */
    public VertexBuffer getVertexBuffer() {
        return vertexBuffer;
    }

    /**
     * Sets the value of the vertexBuffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link VertexBuffer }
     *     
     */
    public void setVertexBuffer(VertexBuffer value) {
        this.vertexBuffer = value;
    }

    /**
     * Gets the value of the world property.
     * 
     * @return
     *     possible object is
     *     {@link World }
     *     
     */
    public World getWorld() {
        return world;
    }

    /**
     * Sets the value of the world property.
     * 
     * @param value
     *     allowed object is
     *     {@link World }
     *     
     */
    public void setWorld(World value) {
        this.world = value;
    }

}
