//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 06:17:17 PM EST 
//


package m3x.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}MeshType">
 *       &lt;sequence>
 *         &lt;element ref="{}Group"/>
 *         &lt;element name="bone" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}InstanceType">
 *                 &lt;attribute name="firstVertex" type="{}UInt32" />
 *                 &lt;attribute name="vertexCount" type="{}UInt32" />
 *                 &lt;attribute name="weight" type="{}Int32" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "group",
    "bone"
})
@XmlRootElement(name = "SkinnedMesh")
public class SkinnedMesh
    extends MeshType
{

    @XmlElement(name = "Group", required = true)
    protected Group group;
    @XmlElement(required = true)
    protected List<SkinnedMesh.Bone> bone;

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link Group }
     *     
     */
    public Group getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link Group }
     *     
     */
    public void setGroup(Group value) {
        this.group = value;
    }

    /**
     * Gets the value of the bone property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bone property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBone().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SkinnedMesh.Bone }
     * 
     * 
     */
    public List<SkinnedMesh.Bone> getBone() {
        if (bone == null) {
            bone = new ArrayList<SkinnedMesh.Bone>();
        }
        return this.bone;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}InstanceType">
     *       &lt;attribute name="firstVertex" type="{}UInt32" />
     *       &lt;attribute name="vertexCount" type="{}UInt32" />
     *       &lt;attribute name="weight" type="{}Int32" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Bone
        extends InstanceType
    {

        @XmlAttribute
        protected Long firstVertex;
        @XmlAttribute
        protected Long vertexCount;
        @XmlAttribute
        protected Integer weight;

        /**
         * Gets the value of the firstVertex property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getFirstVertex() {
            return firstVertex;
        }

        /**
         * Sets the value of the firstVertex property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setFirstVertex(Long value) {
            this.firstVertex = value;
        }

        /**
         * Gets the value of the vertexCount property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getVertexCount() {
            return vertexCount;
        }

        /**
         * Sets the value of the vertexCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setVertexCount(Long value) {
            this.vertexCount = value;
        }

        /**
         * Gets the value of the weight property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getWeight() {
            return weight;
        }

        /**
         * Sets the value of the weight property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setWeight(Integer value) {
            this.weight = value;
        }

    }

}
