//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 06:07:01 PM EST 
//


package m3x.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}TransformableType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{}Image2D" minOccurs="0"/>
 *           &lt;element ref="{}Image2DInstance" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="blendColor" type="{}ColorRGB" />
 *       &lt;attribute name="blending" type="{}Texture2DBlendModeType" />
 *       &lt;attribute name="wrappingS" type="{}Texture2DWrapModeType" />
 *       &lt;attribute name="wrappingT" type="{}Texture2DWrapModeType" />
 *       &lt;attribute name="levelFilter" type="{}TextureMipmapModeType" />
 *       &lt;attribute name="imageFilter" type="{}TextureFilterModeType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "image2D",
    "image2DInstance"
})
@XmlRootElement(name = "Texture2D")
public class Texture2D
    extends TransformableType
{

    @XmlElement(name = "Image2D")
    protected Image2D image2D;
    @XmlElement(name = "Image2DInstance")
    protected Image2DInstance image2DInstance;
    @XmlAttribute
    protected List<Short> blendColor;
    @XmlAttribute
    protected Texture2DBlendModeType blending;
    @XmlAttribute
    protected Texture2DWrapModeType wrappingS;
    @XmlAttribute
    protected Texture2DWrapModeType wrappingT;
    @XmlAttribute
    protected TextureMipmapModeType levelFilter;
    @XmlAttribute
    protected TextureFilterModeType imageFilter;

    /**
     * Gets the value of the image2D property.
     * 
     * @return
     *     possible object is
     *     {@link Image2D }
     *     
     */
    public Image2D getImage2D() {
        return image2D;
    }

    /**
     * Sets the value of the image2D property.
     * 
     * @param value
     *     allowed object is
     *     {@link Image2D }
     *     
     */
    public void setImage2D(Image2D value) {
        this.image2D = value;
    }

    /**
     * Gets the value of the image2DInstance property.
     * 
     * @return
     *     possible object is
     *     {@link Image2DInstance }
     *     
     */
    public Image2DInstance getImage2DInstance() {
        return image2DInstance;
    }

    /**
     * Sets the value of the image2DInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Image2DInstance }
     *     
     */
    public void setImage2DInstance(Image2DInstance value) {
        this.image2DInstance = value;
    }

    /**
     * Gets the value of the blendColor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the blendColor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBlendColor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Short }
     * 
     * 
     */
    public List<Short> getBlendColor() {
        if (blendColor == null) {
            blendColor = new ArrayList<Short>();
        }
        return this.blendColor;
    }

    /**
     * Gets the value of the blending property.
     * 
     * @return
     *     possible object is
     *     {@link Texture2DBlendModeType }
     *     
     */
    public Texture2DBlendModeType getBlending() {
        return blending;
    }

    /**
     * Sets the value of the blending property.
     * 
     * @param value
     *     allowed object is
     *     {@link Texture2DBlendModeType }
     *     
     */
    public void setBlending(Texture2DBlendModeType value) {
        this.blending = value;
    }

    /**
     * Gets the value of the wrappingS property.
     * 
     * @return
     *     possible object is
     *     {@link Texture2DWrapModeType }
     *     
     */
    public Texture2DWrapModeType getWrappingS() {
        return wrappingS;
    }

    /**
     * Sets the value of the wrappingS property.
     * 
     * @param value
     *     allowed object is
     *     {@link Texture2DWrapModeType }
     *     
     */
    public void setWrappingS(Texture2DWrapModeType value) {
        this.wrappingS = value;
    }

    /**
     * Gets the value of the wrappingT property.
     * 
     * @return
     *     possible object is
     *     {@link Texture2DWrapModeType }
     *     
     */
    public Texture2DWrapModeType getWrappingT() {
        return wrappingT;
    }

    /**
     * Sets the value of the wrappingT property.
     * 
     * @param value
     *     allowed object is
     *     {@link Texture2DWrapModeType }
     *     
     */
    public void setWrappingT(Texture2DWrapModeType value) {
        this.wrappingT = value;
    }

    /**
     * Gets the value of the levelFilter property.
     * 
     * @return
     *     possible object is
     *     {@link TextureMipmapModeType }
     *     
     */
    public TextureMipmapModeType getLevelFilter() {
        return levelFilter;
    }

    /**
     * Sets the value of the levelFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextureMipmapModeType }
     *     
     */
    public void setLevelFilter(TextureMipmapModeType value) {
        this.levelFilter = value;
    }

    /**
     * Gets the value of the imageFilter property.
     * 
     * @return
     *     possible object is
     *     {@link TextureFilterModeType }
     *     
     */
    public TextureFilterModeType getImageFilter() {
        return imageFilter;
    }

    /**
     * Sets the value of the imageFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextureFilterModeType }
     *     
     */
    public void setImageFilter(TextureFilterModeType value) {
        this.imageFilter = value;
    }

}
