//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 08:26:55 PM EST 
//


package m3x.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Texture2DBlendModeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Texture2DBlendModeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ADD"/>
 *     &lt;enumeration value="BLEND"/>
 *     &lt;enumeration value="DECAL"/>
 *     &lt;enumeration value="DOT3"/>
 *     &lt;enumeration value="MODULATE"/>
 *     &lt;enumeration value="REPLACE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Texture2DBlendModeType")
@XmlEnum
public enum Texture2DBlendModeType {

    ADD("ADD"),
    BLEND("BLEND"),
    DECAL("DECAL"),
    @XmlEnumValue("DOT3")
    DOT_3("DOT3"),
    MODULATE("MODULATE"),
    REPLACE("REPLACE");
    private final String value;

    Texture2DBlendModeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Texture2DBlendModeType fromValue(String v) {
        for (Texture2DBlendModeType c: Texture2DBlendModeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
