//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.08 at 08:26:55 PM EST 
//


package m3x.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VertexArrayDataType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="VertexArrayDataType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BYTE"/>
 *     &lt;enumeration value="FIXED"/>
 *     &lt;enumeration value="FLOAT"/>
 *     &lt;enumeration value="HALF"/>
 *     &lt;enumeration value="SHORT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "VertexArrayDataType")
@XmlEnum
public enum VertexArrayDataType {

    BYTE,
    FIXED,
    FLOAT,
    HALF,
    SHORT;

    public String value() {
        return name();
    }

    public static VertexArrayDataType fromValue(String v) {
        return valueOf(v);
    }

}
