//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.02 at 11:04:04 PM EST 
//


package m3x.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}Object3DType">
 *       &lt;sequence>
 *         &lt;element name="positions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}translate" minOccurs="0"/>
 *                   &lt;choice>
 *                     &lt;element ref="{}VertexArray"/>
 *                     &lt;element ref="{}VertexArrayInstance"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *                 &lt;attribute name="scale" type="{}float" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="normals" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{}VertexArray"/>
 *                   &lt;element ref="{}VertexArrayInstance"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="colors" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{}VertexArray"/>
 *                   &lt;element ref="{}VertexArrayInstance"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="texcoords" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}translate" minOccurs="0"/>
 *                   &lt;choice>
 *                     &lt;element ref="{}VertexArray"/>
 *                     &lt;element ref="{}VertexArrayInstance"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *                 &lt;attribute name="scale" type="{}float" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="color" type="{}uint" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "positions",
    "normals",
    "colors",
    "texcoords"
})
@XmlRootElement(name = "VertexBuffer")
public class VertexBuffer
    extends Object3DType
{

    @XmlElement(required = true)
    protected VertexBuffer.Positions positions;
    protected VertexBuffer.Normals normals;
    protected VertexBuffer.Colors colors;
    protected List<VertexBuffer.Texcoords> texcoords;
    @XmlAttribute
    protected BigInteger color;

    /**
     * Gets the value of the positions property.
     * 
     * @return
     *     possible object is
     *     {@link VertexBuffer.Positions }
     *     
     */
    public VertexBuffer.Positions getPositions() {
        return positions;
    }

    /**
     * Sets the value of the positions property.
     * 
     * @param value
     *     allowed object is
     *     {@link VertexBuffer.Positions }
     *     
     */
    public void setPositions(VertexBuffer.Positions value) {
        this.positions = value;
    }

    /**
     * Gets the value of the normals property.
     * 
     * @return
     *     possible object is
     *     {@link VertexBuffer.Normals }
     *     
     */
    public VertexBuffer.Normals getNormals() {
        return normals;
    }

    /**
     * Sets the value of the normals property.
     * 
     * @param value
     *     allowed object is
     *     {@link VertexBuffer.Normals }
     *     
     */
    public void setNormals(VertexBuffer.Normals value) {
        this.normals = value;
    }

    /**
     * Gets the value of the colors property.
     * 
     * @return
     *     possible object is
     *     {@link VertexBuffer.Colors }
     *     
     */
    public VertexBuffer.Colors getColors() {
        return colors;
    }

    /**
     * Sets the value of the colors property.
     * 
     * @param value
     *     allowed object is
     *     {@link VertexBuffer.Colors }
     *     
     */
    public void setColors(VertexBuffer.Colors value) {
        this.colors = value;
    }

    /**
     * Gets the value of the texcoords property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the texcoords property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTexcoords().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VertexBuffer.Texcoords }
     * 
     * 
     */
    public List<VertexBuffer.Texcoords> getTexcoords() {
        if (texcoords == null) {
            texcoords = new ArrayList<VertexBuffer.Texcoords>();
        }
        return this.texcoords;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setColor(BigInteger value) {
        this.color = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{}VertexArray"/>
     *         &lt;element ref="{}VertexArrayInstance"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vertexArray",
        "vertexArrayInstance"
    })
    public static class Colors {

        @XmlElement(name = "VertexArray")
        protected VertexArray vertexArray;
        @XmlElement(name = "VertexArrayInstance")
        protected VertexArrayInstance vertexArrayInstance;

        /**
         * Gets the value of the vertexArray property.
         * 
         * @return
         *     possible object is
         *     {@link VertexArray }
         *     
         */
        public VertexArray getVertexArray() {
            return vertexArray;
        }

        /**
         * Sets the value of the vertexArray property.
         * 
         * @param value
         *     allowed object is
         *     {@link VertexArray }
         *     
         */
        public void setVertexArray(VertexArray value) {
            this.vertexArray = value;
        }

        /**
         * Gets the value of the vertexArrayInstance property.
         * 
         * @return
         *     possible object is
         *     {@link VertexArrayInstance }
         *     
         */
        public VertexArrayInstance getVertexArrayInstance() {
            return vertexArrayInstance;
        }

        /**
         * Sets the value of the vertexArrayInstance property.
         * 
         * @param value
         *     allowed object is
         *     {@link VertexArrayInstance }
         *     
         */
        public void setVertexArrayInstance(VertexArrayInstance value) {
            this.vertexArrayInstance = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{}VertexArray"/>
     *         &lt;element ref="{}VertexArrayInstance"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vertexArray",
        "vertexArrayInstance"
    })
    public static class Normals {

        @XmlElement(name = "VertexArray")
        protected VertexArray vertexArray;
        @XmlElement(name = "VertexArrayInstance")
        protected VertexArrayInstance vertexArrayInstance;

        /**
         * Gets the value of the vertexArray property.
         * 
         * @return
         *     possible object is
         *     {@link VertexArray }
         *     
         */
        public VertexArray getVertexArray() {
            return vertexArray;
        }

        /**
         * Sets the value of the vertexArray property.
         * 
         * @param value
         *     allowed object is
         *     {@link VertexArray }
         *     
         */
        public void setVertexArray(VertexArray value) {
            this.vertexArray = value;
        }

        /**
         * Gets the value of the vertexArrayInstance property.
         * 
         * @return
         *     possible object is
         *     {@link VertexArrayInstance }
         *     
         */
        public VertexArrayInstance getVertexArrayInstance() {
            return vertexArrayInstance;
        }

        /**
         * Sets the value of the vertexArrayInstance property.
         * 
         * @param value
         *     allowed object is
         *     {@link VertexArrayInstance }
         *     
         */
        public void setVertexArrayInstance(VertexArrayInstance value) {
            this.vertexArrayInstance = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}translate" minOccurs="0"/>
     *         &lt;choice>
     *           &lt;element ref="{}VertexArray"/>
     *           &lt;element ref="{}VertexArrayInstance"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *       &lt;attribute name="scale" type="{}float" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "translate",
        "vertexArray",
        "vertexArrayInstance"
    })
    public static class Positions {

        @XmlList
        @XmlElement(type = Double.class)
        protected List<Double> translate;
        @XmlElement(name = "VertexArray")
        protected VertexArray vertexArray;
        @XmlElement(name = "VertexArrayInstance")
        protected VertexArrayInstance vertexArrayInstance;
        @XmlAttribute
        protected Double scale;

        /**
         * Gets the value of the translate property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the translate property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTranslate().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Double }
         * 
         * 
         */
        public List<Double> getTranslate() {
            if (translate == null) {
                translate = new ArrayList<Double>();
            }
            return this.translate;
        }

        /**
         * Gets the value of the vertexArray property.
         * 
         * @return
         *     possible object is
         *     {@link VertexArray }
         *     
         */
        public VertexArray getVertexArray() {
            return vertexArray;
        }

        /**
         * Sets the value of the vertexArray property.
         * 
         * @param value
         *     allowed object is
         *     {@link VertexArray }
         *     
         */
        public void setVertexArray(VertexArray value) {
            this.vertexArray = value;
        }

        /**
         * Gets the value of the vertexArrayInstance property.
         * 
         * @return
         *     possible object is
         *     {@link VertexArrayInstance }
         *     
         */
        public VertexArrayInstance getVertexArrayInstance() {
            return vertexArrayInstance;
        }

        /**
         * Sets the value of the vertexArrayInstance property.
         * 
         * @param value
         *     allowed object is
         *     {@link VertexArrayInstance }
         *     
         */
        public void setVertexArrayInstance(VertexArrayInstance value) {
            this.vertexArrayInstance = value;
        }

        /**
         * Gets the value of the scale property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getScale() {
            return scale;
        }

        /**
         * Sets the value of the scale property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setScale(Double value) {
            this.scale = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}translate" minOccurs="0"/>
     *         &lt;choice>
     *           &lt;element ref="{}VertexArray"/>
     *           &lt;element ref="{}VertexArrayInstance"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *       &lt;attribute name="scale" type="{}float" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "translate",
        "vertexArray",
        "vertexArrayInstance"
    })
    public static class Texcoords {

        @XmlList
        @XmlElement(type = Double.class)
        protected List<Double> translate;
        @XmlElement(name = "VertexArray")
        protected VertexArray vertexArray;
        @XmlElement(name = "VertexArrayInstance")
        protected VertexArrayInstance vertexArrayInstance;
        @XmlAttribute
        protected Double scale;

        /**
         * Gets the value of the translate property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the translate property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTranslate().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Double }
         * 
         * 
         */
        public List<Double> getTranslate() {
            if (translate == null) {
                translate = new ArrayList<Double>();
            }
            return this.translate;
        }

        /**
         * Gets the value of the vertexArray property.
         * 
         * @return
         *     possible object is
         *     {@link VertexArray }
         *     
         */
        public VertexArray getVertexArray() {
            return vertexArray;
        }

        /**
         * Sets the value of the vertexArray property.
         * 
         * @param value
         *     allowed object is
         *     {@link VertexArray }
         *     
         */
        public void setVertexArray(VertexArray value) {
            this.vertexArray = value;
        }

        /**
         * Gets the value of the vertexArrayInstance property.
         * 
         * @return
         *     possible object is
         *     {@link VertexArrayInstance }
         *     
         */
        public VertexArrayInstance getVertexArrayInstance() {
            return vertexArrayInstance;
        }

        /**
         * Sets the value of the vertexArrayInstance property.
         * 
         * @param value
         *     allowed object is
         *     {@link VertexArrayInstance }
         *     
         */
        public void setVertexArrayInstance(VertexArrayInstance value) {
            this.vertexArrayInstance = value;
        }

        /**
         * Gets the value of the scale property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getScale() {
            return scale;
        }

        /**
         * Sets the value of the scale property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setScale(Double value) {
            this.scale = value;
        }

    }

}
